autocomplete_entities:
    contacts:
        type: flexible
        form_options:
            extra_config: autocomplete
        entity_class: OroCRM\Bundle\ContactBundle\Entity\Contact
        properties: ["first_name", "last_name"]
