parameters:
    orocrm_contact.contact.datagrid_manager.class:        OroCRM\Bundle\ContactBundle\Datagrid\ContactDatagridManager
    orocrm_contact.group.datagrid_manager.class:          OroCRM\Bundle\ContactBundle\Datagrid\GroupDatagridManager
    orocrm_contact.group_contact.datagrid_manager.class:  OroCRM\Bundle\ContactBundle\Datagrid\GroupContactDatagridManager
    orocrm_contact.contact.view_datagrid_manager.class:   OroCRM\Bundle\ContactBundle\Datagrid\ContactAccountDatagridManager
    orocrm_contact.account.update_datagrid_manager.class: OroCRM\Bundle\ContactBundle\Datagrid\ContactAccountUpdateDatagridManager

services:
    orocrm_contact.contact.datagrid_manager:
        class: %orocrm_contact.contact.datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: contacts
              entity_name: %orocrm_contact.entity.class%
              query_entity_alias: contact
              entity_hint: contacts
              route_name: orocrm_contact_index

    orocrm_contact.group.datagrid_manager:
        class: %orocrm_contact.group.datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: groups
              entity_name: OroCRM\Bundle\ContactBundle\Entity\Group
              entity_hint: groups
              route_name: orocrm_contact_group_index

    orocrm_contact.group_contact.datagrid_manager:
        class: %orocrm_contact.group_contact.datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: groupcontacts
              entity_name: %orocrm_contact.entity.class%
              query_entity_alias: contact
              entity_hint: contacts
              route_name: orocrm_contact_group_contact_grid

    orocrm_contact.account.view_datagrid_manager:
        class: %orocrm_contact.contact.view_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: accounts_view
              entity_name: %orocrm_account.account.entity.class%
              query_entity_alias: account
              entity_hint: acounts
              flexible: true
              route_name: orocrm_contact_view

    orocrm_contact.account.update_datagrid_manager:
        class: %orocrm_contact.account.update_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: accounts_update
              entity_name: %orocrm_account.account.entity.class%
              query_entity_alias: account
              entity_hint: acounts
              flexible: true
              route_name: orocrm_contact_update
