autocomplete_entities:
    contacts:
        type: flexible
        form_options:
            datasource: autocomplete
        options:
            entity_class: OroCRM\Bundle\ContactBundle\Entity\Contact
        properties: ["first_name", "last_name"]