parameters:
    orocrm_contact.importexport.contact_normalizer.class: OroCRM\Bundle\ContactBundle\ImportExport\Serializer\Normalizer\ContactNormalizer
    orocrm_contact.importexport.source_normalizer.class: OroCRM\Bundle\ContactBundle\ImportExport\Serializer\Normalizer\SourceNormalizer
    orocrm_contact.importexport.method_normalizer.class: OroCRM\Bundle\ContactBundle\ImportExport\Serializer\Normalizer\MethodNormalizer
    orocrm_contact.importexport.contact_phone_normalizer.class: OroCRM\Bundle\ContactBundle\ImportExport\Serializer\Normalizer\ContactPhoneNormalizer
    orocrm_contact.importexport.contact_email_normalizer.class: OroCRM\Bundle\ContactBundle\ImportExport\Serializer\Normalizer\ContactEmailNormalizer

services:
    orocrm_contact.importexport.contact_normalizer:
        class: %orocrm_contact.importexport.contact_normalizer.class%
        calls:
            - [setSocialUrlFormatter, [@orocrm_contact.social_url_formatter]]
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_contact.importexport.source_normalizer:
        class: %orocrm_contact.importexport.source_normalizer.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_contact.importexport.method_normalizer:
        class: %orocrm_contact.importexport.method_normalizer.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_contact.importexport.contact_phone_normalizer:
        class: %orocrm_contact.importexport.contact_phone_normalizer.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_contact.importexport.contact_email_normalizer:
        class: %orocrm_contact.importexport.contact_email_normalizer.class%
        tags:
            - { name: oro_importexport.normalizer }
