oro_menu_config:
    items:
        customers_tab:
            label: 'Customers'
            uri: '#'
            extras:
                position: 10
        contact_list:
            label: 'Contacts'
            route: 'orocrm_contact_index'
            extras:
                routes: ['/^orocrm_contact_(?!group\w+|group\w+)\w+$/']
        contact_group_list:
            label: 'Contact Groups'
            route: 'orocrm_contact_group_index'
            extras:
                routes: ['orocrm_contact_group_*']
        shortcut_new_contact:
            label: Create new contact
            route: orocrm_contact_create
            extras:
                description: Create new contact instance
                isCustomAction: true
        shortcut_list_contacts:
            label: Show contacts list
            route: orocrm_contact_index
            extras:
                description: List of contacts

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        contact_list: ~
                        contact_group_list: ~

        shortcuts:
            children:
                shortcut_new_contact: ~
                shortcut_list_contacts: ~

oro_titles:
    orocrm_contact_index: Contacts
    orocrm_contact_view: %%contact.name%% - Contacts
    orocrm_contact_create: Create Contact
    orocrm_contact_update: %%contact.name%% - Contacts

    orocrm_contact_group_index: Contact Groups
    orocrm_contact_group_create: Create Contact Group
    orocrm_contact_group_update: %%group.label%% - Contact Group
