placeholders:
    orocrm_account_action_dropdown:
        items:
            orocrm_account_action_dropdown_add_contact: ~

items:
    orocrm_account_action_dropdown_add_contact:
        template: OroCRMContactBundle:Account:contact.html.twig
