placeholders:
    view_content_data_communications:
        items:
            orocrm_contact_emails: ~

    orocrm_account_action_dropdown:
        items:
            orocrm_account_action_dropdown_add_contact: ~

    quick_launchpad_right_column:
        items:
            leads_launchpad:
                order: 10

items:
    orocrm_account_action_dropdown_add_contact:
        template: OroCRMContactBundle:Account:action/addContactButton.html.twig
        order: 10

    orocrm_contact_emails:
        template: OroCRMContactBundle:Contact:contactEmails.html.twig
        attribute_instance_of: [entity, %orocrm_contact.entity.class%]

    contacts_launchpad:
        template: OroCRMContactBundle:Dashboard:contactsLaunchpad.html.twig
