OroCRM\Bundle\ContactBundle\Entity\Contact:
    alias: orocrm_contact
    label: Contacts
    route:
        name: orocrm_contact_view
        parameters:
            id: id
    search_template: OroCRMContactBundle:Contact:searchResult.html.twig
    entity_icon_class: icon-envelope
    fields:
        -
            name:                   namePrefix
            target_type:            text
            target_fields:          [namePrefix]
        -
            name:                   firstName
            target_type:            text
            target_fields:          [firstName]
        -
            name:                   lastName
            target_type:            text
            target_fields:          [lastName]
        -
            name:                   nameSuffix
            target_type:            text
            target_fields:          [nameSuffix]
        -
            name:                   title
            target_type:            text
            target_fields:          [title]
        -
            name:                   description
            target_type:            text
            target_fields:          [description]
        -
            name:                   source
            relation_type:          many-to-one
            relation_fields:
                -
                    name:           label
                    target_type:    text
                    target_fields:  [label]
        -
            name:                   primaryEmail
            target_type:            text
            target_fields:          [primaryEmail]
        -
            name:                   primaryPhone
            target_type:            text
            target_fields:          [primaryPhone]
