parameters:
    orocrm_contact.serializer.user_handler.class: OroCRM\Bundle\ContactBundle\Serializer\Handler\UserHandler
    orocrm_contact.subscriber.contact_subscriber.class: OroCRM\Bundle\ContactBundle\Serializer\Subscriber\ContactSubscriber

services:
    orocrm_contact.serializer.user_handler:
        class: %orocrm_contact.serializer.user_handler.class%
#        tags:
#            - { name: jms_serializer.subscribing_handler }

    orocrm_contact.subscriber.contact_subscriber:
        class: %orocrm_contact.subscriber.contact_subscriber.class%
#        tags:
#            - { name: jms_serializer.event_subscriber }
