parameters:
    orocrm_contact.manager.flexible.class: Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    orocrm_contact.entity.class: OroCRM\Bundle\ContactBundle\Entity\Contact
    orocrm_contact.entity.value.class: OroCRM\Bundle\ContactBundle\Entity\Value\ContactValue
    orocrm_contact.type.contact.class: OroCRM\Bundle\ContactBundle\Form\Type\ContactType
    orocrm_contact.type.contact_value.class: OroCRM\Bundle\ContactBundle\Form\Type\ContactValueType
    orocrm_contact.type.group.class: OroCRM\Bundle\ContactBundle\Form\Type\GroupType
    orocrm_contact.handler.contact.class: OroCRM\Bundle\ContactBundle\Form\Handler\ContactHandler
    orocrm_contact.attribute_type.contact.class: OroCRM\Bundle\ContactBundle\AttributeType\ContactType
    orocrm_contact.form.type.contact_select.class: OroCRM\Bundle\ContactBundle\Form\Type\ContactSelectType
    orocrm_contact.handler.group.class: OroCRM\Bundle\ContactBundle\Form\Handler\GroupHandler

    orocrm_contact.contact.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiFlexibleEntityManager
    orocrm_contact.type.contact.api.class: OroCRM\Bundle\ContactBundle\Form\Type\ContactApiType

    orocrm_contact.group.entity.class: OroCRM\Bundle\ContactBundle\Entity\Group
    orocrm_contact.group.manager.api.class:  Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    orocrm_contact.type.group.api.class: OroCRM\Bundle\ContactBundle\Form\Type\GroupApiType

    orocrm_contact.contact_address.entity.class: OroCRM\Bundle\ContactBundle\Entity\ContactAddress
    orocrm_contact.contact_address.manager.flexible.class: Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    orocrm_contact.type.contact_address.class: OroCRM\Bundle\ContactBundle\Form\Type\ContactAddressType

services:
    orocrm_contact.manager.flexible:
        class: %orocrm_contact.manager.flexible.class%
        arguments:
            - %orocrm_contact.entity.class%
            - %oro_flexibleentity.flexible_config%
            - @doctrine.orm.entity_manager
            - @event_dispatcher
            - @oro_flexibleentity.attributetype.factory
        calls:
            - [ addAttributeType, ['oro_flexibleentity_text'] ]
            - [ addAttributeType, ['oro_flexibleentity_simpleselect'] ]
            - [ addAttributeType, ['oro_flexibleentity_textarea'] ]
            - [ addAttributeType, ['oro_flexibleentity_date'] ]
            - [ addAttributeType, ['orocrm_account_attribute_account'] ]
            - [ addAttributeType, ['oro_user_attribute_user'] ]
            - [ addAttributeType, ['orocrm_contact_attribute_contact'] ]
            - [ addAttributeType, ['oro_flexibleentity_email_collection'] ]
            - [ addAttributeType, ['oro_flexibleentity_phone_collection'] ]
        tags:
            - { name: oro_flexibleentity_manager, entity: %orocrm_contact.entity.class%}

    orocrm_contact.form.contact:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["orocrm_contact_form", "orocrm_contact", null]

    orocrm_contact.form.group:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["orocrm_contact_group_form", "orocrm_contact_group"]

    orocrm_contact.form.type.contact:
        class: %orocrm_contact.type.contact.class%
        arguments:
            - @orocrm_contact.manager.flexible
            - "orocrm_contact_value"
            - %orocrm_contact.contact_address.entity.class%
        tags:
            - { name: form.type, alias: orocrm_contact }

    orocrm_contact.form.type.contact_value:
        class: %orocrm_contact.type.contact_value.class%
        arguments:
            - @orocrm_contact.manager.flexible
            - @oro_flexibleentity.value_form.value_subscriber
        tags:
            - { name: form.type, alias: orocrm_contact_value }

    orocrm_contact.form.handler.contact:
        class: %orocrm_contact.handler.contact.class%
        scope: request
        arguments:
            - @orocrm_contact.form.contact
            - @request
            - @doctrine.orm.entity_manager

    orocrm_contact.contact.manager:
        class: %orocrm_contact.contact.manager.api.class%
        arguments:
            - %orocrm_contact.entity.class%
            - @doctrine.orm.entity_manager
            - @orocrm_contact.manager.flexible

    # Form type
    orocrm_contact.form.type.contact_select:
        class: %orocrm_contact.form.type.contact_select.class%
        tags:
            - { name: form.type, alias: orocrm_contact_select }

    # Flexible attribute
    orocrm_contact.attribute_type.contact:
        class: %orocrm_contact.attribute_type.contact.class%
        arguments:
            - "contact"
            - "orocrm_contact_select"
            - @oro_flexibleentity.validator.attribute_constraint_guesser
        tags:
            - { name: oro_flexibleentity.attributetype, alias: orocrm_contact_attribute_contact }
    orocrm_contact.form.handler.group:
        class: %orocrm_contact.handler.group.class%
        scope: request
        arguments:
            - @orocrm_contact.form.group
            - @request
            - @doctrine.orm.entity_manager

    orocrm_contact.form.type.group:
        class: %orocrm_contact.type.group.class%
        tags:
            - { name: form.type, alias: orocrm_contact_group }

    # Contact API
    orocrm_contact.contact.manager.api:
        class: %orocrm_contact.contact.manager.api.class%
        arguments:
            - %orocrm_contact.entity.class%
            - @doctrine.orm.entity_manager
            - @orocrm_contact.manager.flexible

    orocrm_contact.form.type.contact.api:
        class: %orocrm_contact.type.contact.api.class%
        arguments:
            - @orocrm_contact.manager.flexible
            - "orocrm_contact_value"
        tags:
            - { name: form.type, alias: contact }

    orocrm_contact.form.contact.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["contact", "contact", null]

    orocrm_contact.form.handler.contact.api:
        class: %orocrm_contact.handler.contact.class%
        scope: request
        arguments:
            - @orocrm_contact.form.contact.api
            - @request
            - @doctrine.orm.entity_manager

    # Group API
    orocrm_contact.group.manager.api:
        class: %orocrm_contact.group.manager.api.class%
        arguments:
            - %orocrm_contact.group.entity.class%
            - @doctrine.orm.entity_manager

    orocrm_contact.form.type.group.api:
        class: %orocrm_contact.type.group.api.class%
        tags:
            - { name: form.type, alias: contact_group }

    orocrm_contact.form.group.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["contact_group", "contact_group", null]

    orocrm_contact.form.handler.group.api:
        class: %orocrm_contact.handler.group.class%
        scope: request
        arguments:
            - @orocrm_contact.form.group.api
            - @request
            - @doctrine.orm.entity_manager

    orocrm_contact.contact_address.manager.flexible:
        class: %orocrm_contact.contact_address.manager.flexible.class%
        arguments:
            - %orocrm_contact.contact_address.entity.class%
            - %oro_flexibleentity.flexible_config%
            - @doctrine.orm.entity_manager
            - @event_dispatcher
            - @oro_flexibleentity.attributetype.factory
        tags:
            - { name: oro_flexibleentity_manager, entity: %orocrm_contact.contact_address.entity.class%}
        calls:
            - [ addAttributeType, ['oro_flexibleentity_text'] ]

    orocrm_contact.type.contact_address:
        class: %orocrm_contact.type.contact_address.class%
        arguments:
            - @orocrm_contact.contact_address.manager.flexible
            - "oro_address_value"
            - @oro_address.form.listener.address
        tags:
            - { name: form.type, alias: orocrm_contact_address }

    orocrm_contact.form.autocomplete.contact.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - %orocrm_contact.entity.class%
            - ["first_name", "last_name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: contacts, acl_resource: orocrm_contact_list }
