OroCRM\Bundle\ContactBundle\Entity\Contact:
    properties:
        firstName:
            - NotBlank:     ~
            - Length:
                max:        100
        lastName:
            - NotBlank:     ~
            - Length:
                max:        100
        birthday:
            - Date:         ~
        email:
            - Email:        ~
        twitterUrl:
            - Url:          ~
        facebookUrl:
            - Url:          ~
        googlePlusUrl:
            - Url:          ~
        linkedInUrl:
            - Url:          ~
        addresses:
            - Oro\Bundle\AddressBundle\Validator\Constraints\ContainsPrimary: ~
            - Oro\Bundle\AddressBundle\Validator\Constraints\UniqueAddressTypes: ~

OroCRM\Bundle\ContactBundle\Entity\Group:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: label
    properties:
        label:
            - NotBlank:     ~
            - Length:
                min:        3
                max:        255
