OroCRM\Bundle\ContactBundle\Entity\Group:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank:     ~
            - Length:
                min:        3
                max:        255

OroCRM\Bundle\ContactBundle\Entity\Contact:
    properties:
        addresses:
            - Oro\Bundle\AddressBundle\Validator\Constraints\ContainsPrimary: ~
            - Oro\Bundle\AddressBundle\Validator\Constraints\UniqueAddressTypes: ~
