imports:
    - { resource: 'ticket_flow/steps.yml' }
    - { resource: 'ticket_flow/attributes.yml' }
    - { resource: 'ticket_flow/transitions.yml' }
    - { resource: 'ticket_flow/transition_definitions.yml' }

workflows:
    ticket_flow:
        label: 'Ticket Flow'
        entity: OroCRM\Bundle\CaseBundle\Entity\Ticket
        entity_attribute: ticket
        start_step: open
