datagrid:
    shopping-carts-grid:
        source:
            type: orm
            query:
                select:
                    - cart
                from:
                    - { table: OroCRM\Bundle\B2CMockBundle\Entity\ShoppingCart, alias: cart }
        columns:
            id:
                label: 'ID'
            customer:
                label: 'Customer'
                frontend_type: string
        options:
            entityHint: shopping carts
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_b2c_shopping_cart_view
                params:     [ id ]
        actions:
            view:
                type: navigate
                label: 'View'
                icon: user
                link: view_link
                rowAction: true
