oro_menu_config:
    items:
        mocks_tab:
            label: 'Mocks'
            uri: '#'
            extras:
                position: 100000
        shopping_cart_list:
            label: 'Shopping carts'
            route: orocrm_b2c_shopping_cart_index
            extras:
                routes: ['orocrm_b2c_shopping_cart_*']
                description: List of shopping carts
        order_list:
            label: 'Orders'
            route: orocrm_b2c_order_index
            extras:
                routes: ['orocrm_b2c_order_*']
                description: List of orders

    tree:
        application_menu:
            children:
                mocks_tab:
                    children:
                        shopping_cart_list: ~
                        order_list: ~
