workflows:
    b2c_flow_shopping_cart:
        label: 'Shopping Cart flow'
        enabled: true
        type: wizard

        steps:
            open:
                label: 'Open'
                #template: 'OroWorkflowBundle:WorkflowStep:edit.html.twig'
                order: 10
                allowed_transitions:
                    - log_call
                    - send_email
                    - convert_to_opportunity
            contacted:
                label: 'Contacted'
                #template: 'OroWorkflowBundle:WorkflowStep:edit.html.twig'
                order: 20
                allowed_transitions:
                    - log_call
                    - send_email
                    - abandon
                    - convert
                    - convert_to_opportunity
            abandoned:
                label: 'Abandoned'
                #template: 'OroWorkflowBundle:WorkflowStep:edit.html.twig'
                order: 30
                allowed_transitions:
                    - reopen
            converted_to_opportunity:
                label: 'Converted to opportunity'
                #template: 'OroWorkflowBundle:WorkflowStep:edit.html.twig'
                order: 30
                allowed_transitions:
                    - reopen
            converted:
                label: 'Converted'
                #template: 'OroWorkflowBundle:WorkflowStep:edit.html.twig'
                order: 30
                allowed_transitions:
                    - reopen

        attributes:
            # Interaction entities
            shopping_cart:
                label: 'Shopping Cart'
                type: entity
                options:
                    class: OroCRM\Bundle\B2CMockBundle\Entity\ShoppingCart
                    managed_entity: true
                    multiple: false
            opportunity:
                label: 'Opportunity'
                type: entity
                options:
                    class: OroCRM\Bundle\SalesBundle\Entity\Opportunity

            # Call related fields
            call:
                label: 'Call log'
                type: entity
                options:
                    class: OroCRM\Bundle\CallBundle\Entity\Call
            phone_number:
                label: 'Phone number'
                type: string
            call_subject:
                label: 'Call subject'
                type: string
            call_date:
                label: 'Call date'
                type: object
                options:
                    class: DateTime
            call_direction:
                label: 'Call direction'
                type: entity
                options:
                    class: OroCRM\Bundle\CallBundle\Entity\CallDirection
            call_status:
                label: 'Call status'
                type: entity
                options:
                    class: OroCRM\Bundle\CallBundle\Entity\CallStatus
            call_duration:
                label: 'Call duration'
                type: object
                options:
                    class: DateTime

            # Email related fields
            email:
                label: 'Email'
                type: entity
                options:
                    class: Oro\Bundle\EmailBundle\Entity\Email
            email_from:
                label: 'Email sender'
                type: string
            email_to:
                label: 'Email recipient'
                type: string
            email_subject:
                label: 'Email subject'
                type: string
            email_body:
                label: 'Email content'
                type: string

            # Other workflow attributes
            notes:
                label: 'Note'
                type: string
            opportunity_name:
                label: 'Opportunity name'
                type: string

        transitions:
            log_call:
                label: 'Log call'
                step_to: contacted
                is_start: true
                frontend_options:
                    icon: 'icon-phone'
                transition_definition: log_call_definition
                form_options:
                    attribute_fields:
                        phone_number:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        call_subject:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        call_date:
                            form_type: oro_date
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        call_direction:
                            form_type: entity
                            options:
                                class: OroCRM\Bundle\CallBundle\Entity\CallDirection
                                property: label
                                required: true
                                constraints:
                                    - NotBlank: ~
                        call_status:
                            form_type: entity
                            options:
                                class: OroCRM\Bundle\CallBundle\Entity\CallStatus
                                property: label
                                required: false
                        call_duration:
                            form_type: time
                            options:
                                required: false
                                widget: single_text
                                with_seconds: true
                        notes:
                            form_type: textarea
                            options:
                                required: false
                    attribute_default_values:
                        phone_number: $shopping_cart.customer.contact.primaryPhone.phone
                        call_subject: 'Shopping cart status refresh'
                    init_actions:
                        - @create_object:
                            class: '\DateTime'
                            attribute: $call_date
                        - @create_object:
                            class: '\DateTime'
                            arguments:
                                - '00:00:00'
                            attribute: $call_duration
            send_email:
                label: 'Send email'
                step_to: contacted
                is_start: true
                frontend_options:
                    icon: 'icon-envelope-alt'
                transition_definition: send_email_definition
                form_options:
                    attribute_fields:
                        email_from:
                            form_type: oro_email_email_address
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                                    - Email: ~
                        email_to:
                            form_type: oro_email_email_address
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                                    - Email: ~
                        email_subject:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        email_body:
                            form_type: textarea
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
                        notes:
                            form_type: textarea
                            options:
                                required: false
                    attribute_default_values:
                        email_to: $shopping_cart.customer.contact.primaryEmail.email
            convert:
                label: 'Convert'
                step_to: converted
                frontend_options:
                    icon: 'icon-shopping-cart'
                    class: 'btn-primary'
                transition_definition: convert_definition
                form_options:
                    attribute_fields:
                        notes:
                            form_type: textarea
            convert_to_opportunity:
                label: 'Convert to opportunity'
                step_to: converted_to_opportunity
                is_start: true
                frontend_options:
                    icon: 'icon-usd'
                transition_definition: convert_to_opportunity_definition
                form_options:
                    attribute_fields:
                        opportunity_name:
                            form_type: text
                            options:
                                required: true
                                constraints:
                                  - NotBlank: ~
                        notes:
                            form_type: textarea
            abandon:
                label: 'Abandon'
                step_to: abandoned
                frontend_options:
                    icon: 'icon-remove-circle'
                    class: 'btn-danger'
                transition_definition: abandon_definition
                form_options:
                    attribute_fields:
                        notes:
                            form_type: textarea
            reopen:
                label: 'Reopen'
                step_to: open
                frontend_options:
                    icon: 'icon-backward'
                transition_definition: reopen_definition
                form_options:
                    attribute_fields:
                        notes:
                            form_type: textarea

        transition_definitions:
            log_call_definition:
                pre_conditions:
                    @equal: [$shopping_cart.status.name, 'open']
                conditions:
                    @and:
                        - @not_empty:
                            parameters: $phone_number
                            message: 'Phone number must be set'
                        - @not_empty:
                            parameters: $call_subject
                            message: 'Call subject must be set'
                        - @not_empty:
                            parameters: $call_date
                            message: 'Call date must be set'
                        - @not_empty:
                            parameters: $call_direction
                            message: 'Call direction must be chosen'
                post_actions:
                     - @create_entity: # create Call
                        class: OroCRM\Bundle\CallBundle\Entity\Call
                        attribute: $call
                        data:
                            relatedContact: $shopping_cart.customer.contact
                            relatedAccount: $shopping_cart.customer.account
                            subject: $call_subject
                            phoneNumber: $phone_number
                            notes: $notes
                            callDateTime: $call_date
                            callStatus: $call_status
                            duration: $call_duration
                            direction: $call_direction

            send_email_definition:
                pre_conditions:
                    @equal: [$shopping_cart.status.name, 'open']
                conditions:
                    @and:
                        - @not_empty:
                            parameters: $email_from
                            message: 'Email sender must be set'
                        - @not_empty:
                            parameters: $email_to
                            message: 'Email recipient must be set'
                        - @not_empty:
                            parameters: $email_subject
                            message: 'Email subject must be set'
                        - @not_empty:
                            parameters: $email_body
                            message: 'Email content must be chosen'
                post_actions:
                     - @send_email: # Send email
                         attribute: $email
                         from: $email_from
                         to: $email_to
                         subject: $email_subject
                         body: $email_body

            convert_definition:
                pre_conditions:
                    @equal: [$shopping_cart.status.name, 'open']
                post_actions:
                    - @find_entity:
                        class: OroCRM\Bundle\B2CMockBundle\Entity\ShoppingCartStatus
                        identifier: 'converted'
                        attribute: $shopping_cart.status

            convert_to_opportunity_definition:
                pre_conditions:
                    @equal: [$shopping_cart.status.name, 'open']
                post_actions:
                    - @find_entity:
                        class: OroCRM\Bundle\B2CMockBundle\Entity\ShoppingCartStatus
                        identifier: 'converted_to_opportunity'
                        attribute: $shopping_cart.status
                    - @create_entity: # create an opportunity
                        class: OroCRM\Bundle\SalesBundle\Entity\Opportunity
                        attribute: $opportunity
                        data:
                            name: $opportunity_name
                            contact: $shopping_cart.customer.contact
                            account: $shopping_cart.customer.account

            abandon_definition:
                pre_conditions:
                    @equal: [$shopping_cart.status.name, 'open']
                post_actions:
                    - @find_entity:
                        class: OroCRM\Bundle\B2CMockBundle\Entity\ShoppingCart
                        identifier: 'lost'
                        attribute: $shopping_cart.status

            reopen_definition:
                conditions:
                    @or:
                        - @equal: [$shopping_cart.status.name, 'converted']
                        - @equal: [$shopping_cart.status.name, 'converted_to_opportunity']
                        - @equal: [$shopping_cart.status.name, 'lost']
                post_actions:
                    - @find_entity:
                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityStatus
                        identifier: 'open'
                        attribute: $shopping_cart.status