entities_config:
    Oro\Bundle\ContactBundle\Entity\Contact:
        flexible_manager:     oro_contact.manager.flexible
        flexible_class:       %oro_contact.entity.class%
        flexible_value_class: %oro_contact.entity.value.class%
        flexible_init_mode:   all_attributes