entities_config:
    Oro\Bundle\AccountBundle\Entity\Account:
        flexible_manager:     oro_account.account.manager.flexible
        flexible_class:       %oro_account.account.entity.class%
        flexible_value_class: %oro_account.account.entity.value.class%
        flexible_init_mode:   all_attributes