oro_menu_config:
    items:
        customers_tab:
            label: 'Customers'
            uri: '#'
            extras:
                position: 10
        account_list:
            label: 'Accounts'
            route: 'oro_account_index'
            extras:
                routes: ['oro_account_*']

        shortcut_new_account:
            label: Create new account
            route: oro_account_create
            extras:
                description: Create new account instance
                isCustomAction: true
        shortcut_list_accounts:
            label: Show accounts list
            route: oro_account_index
            extras:
                description: List of accounts

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        account_list: ~

        shortcuts:
            children:
                shortcut_new_account: ~
                shortcut_list_accounts: ~

oro_titles:
    oro_account_index: Accounts
    oro_account_view: %%account.name%% - View Account
    oro_account_create: New Account
    oro_account_update: %%account.name%% - Edit Account
