oro_menu_config:
    items:
        customers_tab:
            label: 'Customers'
            uri: '#'
            extras:
                position: 10
        contact_list:
            label: 'Contacts'
            route: 'oro_contact_index'
            extras:
                routes: ['/^oro_contact_(?!group\w+|group\w+)\w+$/']
        contact_group_list:
            label: 'Contact Groups'
            route: 'oro_contact_group_index'
            extras:
                routes: ['oro_contact_group_*']
        shortcut_new_contact:
            label: Create new contact
            route: oro_contact_create
            extras:
                description: Create new contact instance
                isCustomAction: true
        shortcut_list_contacts:
            label: Show contacts list
            route: oro_contact_index
            extras:
                description: List of contacts

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        contact_list: ~
                        contact_group_list: ~

        shortcuts:
            children:
                shortcut_new_contact: ~
                shortcut_list_contacts: ~

oro_titles:
    oro_contact_index: Contacts
    oro_contact_view: %%contact.name%% - Contacts
    oro_contact_create: Create Contact
    oro_contact_update: %%contact.name%% - Contacts

    oro_contact_group_index: Contact Groups
    oro_contact_group_create: Create Contact Group
    oro_contact_group_update: %%group.name%% - Contact Group
