oro_account_bundle:
    resource:     "@OroAccountBundle/Controller"
    type:         annotation
    prefix:       /account

oro_account_api_account:
    resource:     "@OroAccountBundle/Controller/Api/Rest/AccountController.php"
    type:         rest
    prefix:       api/rest/{version}/
    defaults:
        version:  latest
