orocrm_contact_bundle:
    resource:     "@OroCRMContactBundle/Controller"
    type:         annotation
    prefix:       /contact

orocrm_contact_api:
    resource:     "@OroCRMContactBundle/Controller/Api/Rest/ContactController.php"
    type:         rest
    prefix:       api/rest/{version}/
    defaults:
        version:  latest

orocrm_contact_group_api:
    resource:     "@OroCRMContactBundle/Controller/Api/Rest/ContactGroupController.php"
    type:         rest
    prefix:       api/rest/{version}/
    defaults:
        version:  latest
