Oro\Bundle\ContactBundle\Entity\Contact:
    alias: oro_contact
    label: Contacts
    flexible_manager: oro_contact.manager.flexible
    route:
        name: oro_contact_view
        parameters:
            id: id
    search_template: OroContactBundle:Contact:searchResult.html.twig
    entity_icon: bundles/orocontact/img/search.png
    fields: []
