Oro\Bundle\AccountBundle\Entity\Account:
    alias: oro_account
    label: Accounts
    flexible_manager: oro_account.account.manager.flexible
    title_fields: [name]
    route:
        name: oro_account_view
        parameters:
            id: id
    search_template: OroAccountBundle:Account:searchResult.html.twig
    entity_icon: bundles/oroaccount/img/search.png
    fields:
        -
            name: name
            target_type: text
            target_fields: [name]
