parameters:
    oro_contact.manager.class: Oro\Bundle\ContactBundle\Entity\Manager\ContactManager
    oro_contact.manager.flexible.class: Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    oro_contact.entity.class: Oro\Bundle\ContactBundle\Entity\Contact
    oro_contact.entity.value.class: Oro\Bundle\ContactBundle\Entity\Value\ContactValue
    oro_contact.type.contact.class: Oro\Bundle\ContactBundle\Form\Type\ContactType
    oro_contact.type.contact_value.class: Oro\Bundle\ContactBundle\Form\Type\ContactValueType
    oro_contact.handler.contact.class: Oro\Bundle\ContactBundle\Form\Handler\ContactHandler
    oro_contact.attribute_type.contact.class: Oro\Bundle\ContactBundle\AttributeType\ContactType
    oro_contact.form.type.contact_select.class: Oro\Bundle\ContactBundle\Form\Type\ContactSelectType

services:
    oro_contact.manager.flexible:
        class: %oro_contact.manager.flexible.class%
        arguments:
            - %oro_contact.entity.class%
            - %oro_flexibleentity.flexible_config%
            - @doctrine.orm.entity_manager
            - @event_dispatcher
            - @oro_flexibleentity.attributetype.factory
        calls:
            - [ addAttributeType, ['oro_flexibleentity_text'] ]
            - [ addAttributeType, ['oro_flexibleentity_simpleselect'] ]
            - [ addAttributeType, ['oro_flexibleentity_textarea'] ]
            - [ addAttributeType, ['oro_flexibleentity_date'] ]
            - [ addAttributeType, ['oro_account_attribute_account'] ]
            - [ addAttributeType, ['oro_user_attribute_user'] ]
            - [ addAttributeType, ['oro_contact_attribute_contact'] ]
        tags:
            - { name: oro_flexibleentity_manager, entity: %oro_contact.entity.class%}

    oro_contact.manager:
        class: %oro_contact.manager.class%
        arguments:
            - %oro_contact.entity.class%
            - @doctrine.orm.entity_manager
            - @oro_contact.manager.flexible

    oro_contact.form.contact:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["oro_contact_form", "oro_contact", null]

    oro_contact.form.type.contact:
        class: %oro_contact.type.contact.class%
        arguments:
            - @oro_contact.manager.flexible
            - "oro_contact_value"
        tags:
            - { name: form.type, alias: oro_contact }

    oro_contact.form.type.contact_value:
        class: %oro_contact.type.contact_value.class%
        arguments:
            - @oro_contact.manager.flexible
        tags:
            - { name: form.type, alias: oro_contact_value }

    oro_contact.form.handler.contact:
        class: %oro_contact.handler.contact.class%
        scope: request
        arguments:
            - @oro_contact.form.contact
            - @request
            - @doctrine.orm.entity_manager

    # Form type
    oro_contact.form.type.contact_select:
        class: %oro_contact.form.type.contact_select.class%
        tags:
            - { name: form.type, alias: oro_contact_select }

    # Flexible attribute
    oro_contact.attribute_type.contact:
        class: %oro_contact.attribute_type.contact.class%
        arguments:
            - @translator
            - "contact"
            - "oro_contact_select"
        tags:
            - { name: oro_flexibleentity.attributetype, alias: oro_contact_attribute_contact }