parameters:
    oro_account.account.manager.flexible.class: Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    oro_account.account.entity.class: Oro\Bundle\AccountBundle\Entity\Account
    oro_account.account.entity.value.class: Oro\Bundle\AccountBundle\Entity\Value\AccountValue
    oro_account.type.account.class: Oro\Bundle\AccountBundle\Form\Type\AccountType
    oro_account.type.account_value.class: Oro\Bundle\AccountBundle\Form\Type\AccountValueType
    oro_account.handler.account.class: Oro\Bundle\AccountBundle\Form\Handler\AccountHandler
    oro_account.attribute_type.account.class: Oro\Bundle\AccountBundle\AttributeType\AccountType
    oro_account.form.type.account_select.class: Oro\Bundle\AccountBundle\Form\Type\AccountSelectType

    oro_account.account.manager.api.class:  Oro\Bundle\SoapBundle\Entity\Manager\ApiFlexibleEntityManager
    oro_account.type.account.api.class: Oro\Bundle\AccountBundle\Form\Type\AccountApiType

services:
    oro_account.account.manager.flexible:
        class: %oro_account.account.manager.flexible.class%
        arguments:
            - %oro_account.account.entity.class%
            - %oro_flexibleentity.flexible_config%
            - @doctrine.orm.entity_manager
            - @event_dispatcher
            - @oro_flexibleentity.attributetype.factory
        calls:
            - [ addAttributeType, ['oro_flexibleentity_text'] ]
            - [ addAttributeType, ['oro_flexibleentity_integer'] ]
            - [ addAttributeType, ['oro_flexibleentity_textarea'] ]
            - [ addAttributeType, ['oro_flexibleentity_money'] ]
            - [ addAttributeType, ['oro_flexibleentity_url'] ]
            - [ addAttributeType, ['oro_flexibleentity_email_collection'] ]
            - [ addAttributeType, ['oro_flexibleentity_phone_collection'] ]
            - [ addAttributeType, ['oro_address'] ]
        tags:
            - { name: oro_flexibleentity_manager, entity: %oro_account.account.entity.class%}

    oro_account.form.account:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["oro_account_form", "oro_account", null]

    oro_account.form.type.account:
        class: %oro_account.type.account.class%
        arguments:
            - @oro_account.account.manager.flexible
            - "oro_account_value"
        tags:
            - { name: form.type, alias: oro_account }

    oro_account.form.type.account_value:
        class: %oro_account.type.account_value.class%
        arguments:
            - @oro_account.account.manager.flexible
            - @oro_flexibleentity.value_form.value_subscriber
        tags:
            - { name: form.type, alias: oro_account_value }

    oro_account.form.handler.account:
        class: %oro_account.handler.account.class%
        scope: request
        arguments:
            - @oro_account.form.account
            - @request
            - @doctrine.orm.entity_manager

    # Form type
    oro_account.form.type.account_select:
        class: %oro_account.form.type.account_select.class%
        tags:
            - { name: form.type, alias: oro_account_select }

    # Flexible attribute
    oro_account.attribute_type.account:
        class: %oro_account.attribute_type.account.class%
        arguments:
            - "account"
            - "oro_account_select"
        tags:
            - { name: oro_flexibleentity.attributetype, alias: oro_account_attribute_account }

    # Account API
    oro_account.account.manager.api:
        class: %oro_account.account.manager.api.class%
        arguments:
            - %oro_account.account.entity.class%
            - @doctrine.orm.entity_manager
            - @oro_account.account.manager.flexible

    oro_account.form.type.account.api:
        class: %oro_account.type.account.api.class%
        arguments:
            - @oro_account.account.manager.flexible
            - "oro_account_value"
        tags:
            - { name: form.type, alias: account }

    oro_account.form.account.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["account", "account", null]

    oro_account.form.handler.account.api:
        class: %oro_account.handler.account.class%
        scope: request
        arguments:
            - @oro_account.form.account.api
            - @request
            - @doctrine.orm.entity_manager
