parameters:
#    oro_contact.example.class: Oro\Bundle\ContactBundle\Example

services:
#    oro_contact.example:
#        class: %oro_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
