parameters:
    oro_contact.contact.manager.class: Oro\Bundle\ContactBundle\Entity\Manager\ContactManager
    oro_contact.contact.manager.flexible.class: Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    oro_contact.contact.entity.class: Oro\Bundle\ContactBundle\Entity\Contact
    oro_contact.contact.entity.value.class: Oro\Bundle\ContactBundle\Entity\Value\ContactValue
    oro_contact.type.contact.class: Oro\Bundle\ContactBundle\Form\Type\ContactType
    oro_contact.handler.contact.class: Oro\Bundle\ContactBundle\Form\Handler\ContactHandler

services:
    oro_contact.contact.manager.flexible:
        class: %oro_contact.contact.manager.flexible.class%
        arguments:
            - %oro_contact.contact.entity.class%
            - %oro_flexibleentity.flexible_config%
            - @doctrine.orm.entity_manager
            - @event_dispatcher
        tags:
            - { name: oro_flexibleentity_manager, entity: %oro_contact.contact.entity.class%}

    oro_contact.contact.manager:
        class: %oro_contact.contact.manager.class%
        arguments:
            - %oro_contact.contact.entity.class%
            - @doctrine.orm.entity_manager
            - @oro_contact.contact.manager.flexible

    oro_contact.form.contact:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["oro_contact_form", "oro_contact", null]

    oro_contact.form.type.contact:
        class: %oro_contact.type.contact.class%
        arguments:
            - %oro_contact.contact.entity.class%
            - %oro_contact.contact.entity.value.class%
        tags:
             - { name: form.type, alias: oro_contact }

    oro_contact.form.handler.contact:
        class: %oro_contact.handler.contact.class%
        scope: request
        arguments:
            - @oro_contact.form.contact
            - @request
            - @doctrine.orm.entity_manager
