parameters:
    oro_account.account.manager.class: Oro\Bundle\AccountBundle\Entity\Manager\AccountManager
    oro_account.account.manager.flexible.class: Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    oro_account.account.entity.class: Oro\Bundle\AccountBundle\Entity\Account
    oro_account.account.entity.value.class: Oro\Bundle\AccountBundle\Entity\Value\AccountValue
    oro_account.type.account.class: Oro\Bundle\AccountBundle\Form\Type\AccountType
    oro_account.handler.account.class: Oro\Bundle\AccountBundle\Form\Handler\AccountHandler

services:
    oro_account.account.manager.flexible:
        class: %oro_account.account.manager.flexible.class%
        arguments:
            - %oro_account.account.entity.class%
            - %oro_flexibleentity.flexible_config%
            - @doctrine.orm.entity_manager
            - @event_dispatcher
        tags:
            - { name: oro_flexibleentity_manager, entity: %oro_account.account.entity.class%}

    oro_account.account.manager:
        class: %oro_account.account.manager.class%
        arguments:
            - %oro_account.account.entity.class%
            - @doctrine.orm.entity_manager
            - @oro_account.account.manager.flexible

    oro_account.form.account:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["oro_account_form", "oro_account", null]

    oro_account.form.type.account:
        class: %oro_account.type.account.class%
        arguments:
            - %oro_account.account.entity.class%
            - %oro_account.account.entity.value.class%
        tags:
             - { name: form.type, alias: oro_account }

    oro_account.form.handler.account:
        class: %oro_account.handler.account.class%
        scope: request
        arguments:
            - @oro_account.form.account
            - @request
            - @doctrine.orm.entity_manager