services:
    orocrm.report.filter.type.period:
        class: OroCRM\Bundle\ReportBundle\Filter\PeriodFilter
        arguments:
            - @form.factory
            - @translator
        tags:
            - { name: oro_grid.filter.type, alias: orocrm_period_filter }
