parameters:
    orocrm_report.report.entity.class:                    OroCRM\Bundle\ReportBundle\Entity\Report
    orocrm_report.form.type.report.class:                 OroCRM\Bundle\ReportBundle\Form\Type\ReportType
    orocrm_report.form.type.entity_choice.class:          OroCRM\Bundle\ReportBundle\Form\Type\ReportEntityChoiceType
    orocrm_report.form.type.entity_field_choice.class:    OroCRM\Bundle\ReportBundle\Form\Type\ReportEntityFieldChoiceType
    orocrm_report.form.handler.report.class:              OroCRM\Bundle\ReportBundle\Form\Handler\ReportHandler
    orocrm_report.report.manager.api.class:               Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    orocrm_report.form.type.report:
        class: %orocrm_report.form.type.report.class%
        tags:
            - { name: form.type, alias: orocrm_report }

    orocrm_report.form.report:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_report_form"
            - "orocrm_report"

    orocrm_report.form.handler.report:
        class: %orocrm_report.form.handler.report.class%
        scope: request
        arguments:
            - @orocrm_report.form.report
            - @request
            - @doctrine.orm.entity_manager

    orocrm_report.report.manager.api:
        class: %orocrm_report.report.manager.api.class%
        arguments:
            - %orocrm_report.report.entity.class%
            - @doctrine.orm.entity_manager

    orocrm_report.form.type.entity_choice:
        class: %orocrm_report.form.type.entity_choice.class%
        arguments:
            - @orocrm_report.entity_provider
        tags:
            - { name: form.type, alias: orocrm_report_entity_choice }

    orocrm_report.form.type.entity_field_choice:
        class: %orocrm_report.form.type.entity_field_choice.class%
        arguments:
            - @orocrm_report.entity_field_provider
            - @translator
        tags:
            - { name: form.type, alias: orocrm_report_entity_field_choice }
