oro_menu_config:
    items:
        reports_tab:
            label: 'Reports'
            uri: '#'
            extras:
                position: 30

        accounts_report_tab:
            label: 'Accounts'
            uri: '#'
            extras:
                position: 10
                
        leads_report_tab:
            label: 'Leads'
            uri: '#'
            extras:
                position: 20
                
        accounts_life_time_value:
            label: 'Life Time'
            route: 'orocrm_report_index'
            routeParameters:
                reportGroupName: accounts
                reportName:      life_time_value

        accounts_by_opportunities:
            label: 'By Opportunities'
            route: 'orocrm_report_index'
            routeParameters:
                reportGroupName: accounts
                reportName:      by_opportunities

        leads_by_date:
            label: 'Leads by date'
            route: 'orocrm_report_index'
            routeParameters:
                reportGroupName: leads
                reportName:      by_date

    tree:
        application_menu:
            children:
                reports_tab:
                    children:
                        accounts_report_tab:
                            children:
                                accounts_life_time_value: ~
                                accounts_by_opportunities: ~

                        leads_report_tab:
                            children:
                                leads_by_date: ~

oro_titles:
    orocrm_report_index: %%reportName%% - Reports
