oro_menu_config:
    items:
        divider:
            uri: '#'
            attributes:
                class: divider

        reports_tab:
            label: 'Reports'
            uri: '#'
            extras:
                position: 30

        manage_reports:
            label: 'Manage Reports'
            route: 'orocrm_report_index'

    tree:
        application_menu:
            children:
                reports_tab:
                    children:
                        manage_reports: ~
                        divider: ~
                        accounts_report_tab:
                            children:
                                accounts_life_time_value: ~
                                accounts_by_opportunities: ~

                        leads_report_tab:
                            children:
                                leads_by_date: ~

                        opportunities_report_tab:
                            children:
                                opportunities_by_step: ~
                                won_by_period: ~

oro_titles:
    orocrm_report_index: ~
    orocrm_report_view:   %%report.name%% - Reports
    orocrm_report_create: Create Report - Reports
    orocrm_report_update: %%report.name%% - Edit - Reports
