oro_menu_config:
    items:
        reports_tab:
            label: 'Reports'
            uri: '#'
            extras:
                position: 30

        accounts_report_tab:
            label: 'Accounts'
            uri: '#'
            extras:
                position: 10

        accounts_life_time_value:
            label: 'Life Time'
            route: 'orocrm_report_index'
            routeParameters:
                reportGroupName: accounts
                reportName:      life_time_value

        accounts_by_opportunities:
            label: 'by Opportunities'
            route: 'orocrm_report_index'
            routeParameters:
                reportGroupName: accounts
                reportName:      by_opportunities

    tree:
        application_menu:
            children:
                reports_tab:
                    children:
                        accounts_report_tab:
                            children:
                                accounts_life_time_value: ~
                                accounts_by_opportunities: ~

oro_titles:
    orocrm_report_index: %%reportName%% - Accounts - Reports
