oro_menu_config:
    items:
        reports_tab:
            label: 'Reports'
            uri: '#'
            extras:
                position: 30

        manage_reports:
            label: 'Manage Reports'
            route: 'orocrm_report_index'

    tree:
        application_menu:
            children:
                reports_tab:
                    children:
                        manage_reports: ~

oro_titles:
    orocrm_report_index: ~
    orocrm_report_view:   %%report.name%% - Reports
    orocrm_report_create: Create Report - Reports
    orocrm_report_update: %%report.name%% - Edit - Reports
