query_designer:
    aggregates:
        opportunity_by_workflow_item_close_revenue:
            applicable: [{parent_entity: OroCRMReportBundle:OpportunityByWorkflowItem, entity: OroCRMSalesBundle:Opportunity, field: closeRevenue}]
            functions:
                - { name: ClosedCloseRevenueSum, expr: @OroCRM\Bundle\ReportBundle\QueryDesigner\CloseRevenueSumFunction }
            query_type: [report]
