reports:
    opportunities:
        by_step:
            name: "Opportunities by step"
            from:
                - { table: OroCRMReportBundle:OpportunityByWorkflowItem, alias: owi }
            select:
                - wi.currentStepName
                - o.name
                - COUNT(o.id) as numberOfOpp
                - >
                  SUM(
                    (CASE WHEN (wi.currentStepName='close') THEN o.closeRevenue ELSE 0 END)
                  ) as closeRevenue
                - >
                  SUM(
                    (CASE WHEN (o.budgetAmount IS NOT NULL) THEN o.budgetAmount ELSE 0 END)
                  ) as budgetAmount
                # for filtering
                - wi.workflowName
            join:
                inner:
                    - { join: owi.opportunity, alias: o }
                    - { join: owi.workflowItem, alias: wi }
            groupBy:  "wi.currentStepName"

        won_by_period:
            name: "Won opportunities by date period"
            from:
                - { table: OroCRMSalesBundle:Opportunity, alias: o }
            select:
                - CONCAT( CONCAT( SUBSTRING( o.closeDate, 6, 2 ), ' / '), SUBSTRING( o.closeDate, 1, 4 ) ) as monthPeriod
                - >
                  CONCAT(
                    CASE
                      WHEN SUBSTRING(o.closeDate, 6, 2) BETWEEN 1 AND 3 THEN '1'
                      WHEN SUBSTRING(o.closeDate, 6, 2) BETWEEN 4 AND 6 THEN '2'
                      WHEN SUBSTRING(o.closeDate, 6, 2) BETWEEN 7 AND 9 THEN '3'
                      ELSE '4'
                    END,
                    CONCAT(' / ' , SUBSTRING( o.closeDate, 1, 4 ) ) as quarterPeriod
                - SUBSTRING( o.closeDate, 1, 4 ) as yearPeriod
                - SUM( o.closeRevenue ) as value
                - COUNT( o.id ) as cnt
            join:
                inner:
                    - { join: o.status, alias: s }
            where:
                and:
                    - s.name = 'won'
                    - o.closeDate IS NOT NULL
