reports:
    accounts:
        life_time_value:
            name:   "Account Life Time Value"
            select: "u.username, u.firstName, u.loginCount"
            from:
                - { table: OroUserBundle:User, alias: u }

    leads: ~
