reports:
    accounts:
        life_time_value:
            name:   "Account Life Time Value"
            select: "u.username, u.firstName, u.loginCount"
            from:
                - { table: OroUserBundle:User, alias: u }

        by_opportunities:
            name:     "Accounts by Opportunities"
            from:
                - { table: OroCRMSalesBundle:Opportunity, alias: o }
            select: >
                a.id,
                a.name,
                SUM( (CASE WHEN (s.name='won') THEN 1 ELSE 0 END) ) as won,
                SUM( (CASE WHEN (s.name='lost') THEN 1 ELSE 0 END) ) as lost,
                SUM( (CASE WHEN (s.name='in_progress') THEN 1 ELSE 0 END) ) as in_progress,
                COUNT(o.id) as total_ops
            join:
                left:
                    - { join: o.account, alias: a }
                    - { join: o.status, alias: s }
                    - { join: o.closeReason, alias: cr }
#            where:
#                and:
#                    - "u.loginCount >= 0"
#                or:
#                    - "u.enabled = 0"
            groupBy:  "a.id"
#            having:   "COUNT(u.firstName) > 1"
#            orderBy:
#                - { column: "a.name", dir: "asc" }

        mage_order_state:
            name:     MageOrderState
            select:   "m.createdAt, m.state, SUM(m.orderCount) AS orderCount, AVG(m.avgBaseGrandTotal) AS avgTotal"
            from:
                - { table: AcmeDemoBundle:ReportMage\ReportMageOrderState, alias: m }
            groupBy:  "m.createdAt, m.state"
            orderBy:
                - { column: "m.createdAt", dir: "desc" }
                - { column: "avgTotal" }

    leads: ~
