reports:
    accounts:
        life_time_value:
            name:   "Account Life Time Value"
            select:
                - a.name
                - SUM( o.closeRevenue ) as value
            from:
                - { table: OroCRMSalesBundle:Opportunity, alias: o }
            join:
                left:
                    - { join: o.account, alias: a }
                    - { join: o.status,  alias: s }
            where:
                and:
                    - s.name = 'won'

            groupBy:  a.id

    leads:
        by_date:
            name:      "Number Leads by date"
            select:
                - COUNT(l.id) as leadsCount
                - SUBSTRING(l.createdAt, 1, 10) as createdDate
            from:
                - { table: OroCRMSalesBundle:Lead, alias: l }

            groupBy: createdDate
