reports:
    accounts:
        life_time_value:
            name:   "Account Life Time Value"
            select:
                - a.name
                - SUM( o.closeRevenue ) as value
            from:
                - { table: OroCRMSalesBundle:Opportunity, alias: o }
            join:
                left:
                    - { join: o.account, alias: a }
                    - { join: o.status,  alias: s }
            where:
                and:
                    - s.name = 'won'

            groupBy:  a.id

        by_opportunities:
            name:     "Accounts by Opportunities"
            from:
                - { table: OroCRMSalesBundle:Opportunity, alias: o }
            select:
                - a.id
                - a.name
                - SUM( (CASE WHEN (s.name='won') THEN 1 ELSE 0 END) ) as wonCount
                - SUM( (CASE WHEN (s.name='lost') THEN 1 ELSE 0 END) ) as lostCount
                - SUM( (CASE WHEN (s.name='in_progress') THEN 1 ELSE 0 END) ) as inProgressCount
                - COUNT(o.id) as total_ops
            join:
                left:
                    - { join: o.account, alias: a }
                    - { join: o.status, alias: s }
                    - { join: o.closeReason, alias: cr }
            groupBy:  "a.id"

    opportunities:
        by_step:
            name: "Opportunities by Step"
            from:
                - { table: OroCRMReportBundle:OpportunityByWorkflowItem, alias: owi }
            select:
                - wi.currentStepName
                - o.name
                - COUNT(o.id) as total_ops
            join:
                left:
                    - { join: owi.opportunity, alias: o }
                    - { join: owi.workflowItem, alias: wi }
            groupBy:  "wi.currentStepName"

    leads:
        by_date:
            name:      "Number Leads by date"
            select:
                - COUNT(l.id) as leadsCount
                - SUBSTRING(l.createdAt, 1, 10) as createdDate
            from:
                - { table: OroCRMSalesBundle:Lead, alias: l }

            groupBy: createdDate
