parameters:
    orocrm_report.report.filter.type.period.class:        OroCRM\Bundle\ReportBundle\Filter\PeriodFilter
    orocrm_report.report.grid.listener.class:             OroCRM\Bundle\ReportBundle\EventListener\ReportGridListener
    orocrm_report.datagrid.configuration.provider.class:  OroCRM\Bundle\ReportBundle\Grid\ReportDatagridConfigurationProvider

services:
    orocrm_report.report.filter.type.period:
        class: %orocrm_report.report.filter.type.period.class%
        arguments:
            - @form.factory
            - @oro_filter.extension.filter_utility
        tags:
            - { name:oro_filter.extension.orm_filter.filter, type: orocrm_period_filter }

    orocrm_report.report.grid.listener:
        class: %orocrm_report.report.grid.listener.class%
        arguments:
            - @oro_datagrid.datagrid.request_params
        tags:
            -
                name:   kernel.event_listener
                event:  oro_datagrid.datgrid.build.before.orocrm_report-opportunities-won_by_period
                method: onBuildBefore

    orocrm_report.datagrid.configuration.provider:
        class: %orocrm_report.datagrid.configuration.provider.class%
        arguments:
            - @doctrine
        tags:
            - { name: oro_datagrid.configuration.provider }

    orocrm_report.entity_provider:
        alias: oro_entity.entity_provider

    orocrm_report.entity_field_provider:
        class: %oro_entity.entity_field_provider.class%
        arguments:
            - @oro_entity_config.provider.entity
            - @oro_entity.orm.entity_class_resolver
            - @doctrine
            - @orocrm_report.entity_provider
