parameters:
#    oro_crm_report.example.class: OroCRM\Bundle\ReportBundle\Example

services:
#    oro_crm_report.example:
#        class: %oro_crm_report.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
