OroCRM\Bundle\AccountBundle\Entity\Account:
    fields:
        extend_description:
            type:                 text
            configs:
                datagrid:
                    is_visible:   false
                merge:
                    display:       true
            owner:                Custom
            is_extend:            true

        extend_phone:
            type:                 string
            configs:
                datagrid:
                    is_visible:   false
                merge:
                    display:       true
            owner:                Custom
            is_extend:            true

        extend_email:
            type:                 string
            configs:
                datagrid:
                    is_visible:   false
                merge:
                    display:       true
            owner:                Custom
            is_extend:            true

        extend_fax:
            type:                 string
            configs:
                datagrid:
                    is_visible:   false
                merge:
                    display:       true
            owner:                Custom
            is_extend:            true

        extend_website:
            type:                 string
            configs:
                datagrid:
                    is_visible:   false
                merge:
                    display:       true
            owner:                Custom
            is_extend:            true

        extend_employees:
            type:                 integer
            configs:
                datagrid:
                    is_visible:   false
                merge:
                    display:       true
            owner:                Custom
            is_extend:            true

        extend_ownership:
            type:                 string
            configs:
                datagrid:
                    is_visible:   false
                merge:
                    display:       true
            owner:                Custom
            is_extend:            true

        extend_ticker_symbol:
            type:                 string
            configs:
                datagrid:
                    is_visible:   false
                merge:
                    display:       true
            owner:                Custom
            is_extend:            true

        extend_rating:
            type:                 string
            configs:
                datagrid:
                    is_visible:   false
                merge:
                    display:       true
            owner:                Custom
            is_extend:            true
