OroCRM\Bundle\AccountBundle\Entity\Account:
    fields:
        add_description:
            type:           text
            configs:
                entity:
                    label:  Description
            owner:          Custom
            is_extend:      true
        add_phone:
            type:           string
            configs:
                entity:
                    label:  Phone
            owner:          Custom
            is_extend:      true
        add_email:
            type:           string
            configs:
                entity:
                    label:  Email
            owner:          Custom
            is_extend:      true
        add_fax:
            type:           string
            configs:
                entity:
                    label:  Fax
            owner:          Custom
            is_extend:      true
        add_website:
            type:           string
            configs:
                entity:
                    label:  Website
            owner:          Custom
            is_extend:      true
        add_employees:
            type:           integer
            configs:
                entity:
                    label:  Employees
            owner:          Custom
            is_extend:      true
        add_ownership:
            type:           string
            configs:
                entity:
                    label:  Ownership
            owner:          Custom
            is_extend:      true
        add_ticker_symbol:
            type:           string
            configs:
                entity:
                    label:  Ticker Symbol
            owner:          Custom
            is_extend:      true
        add_rating:
            type:           string
            configs:
                entity:
                    label:  Rating
            owner:          Custom
            is_extend:      true
