OroCRM\Bundle\AccountBundle\Entity\Account:
    fields:
        add_description:
            type:                 text
            configs:
                entity:
                    label:        Description
                datagrid:
                    is_visible:   false
            owner:                Custom
            is_extend:            true

        add_phone:
            type:                 string
            configs:
                entity:
                    label:        Phone
                datagrid:
                    is_visible:   false
            owner:                Custom
            is_extend:            true

        add_email:
            type:                 string
            configs:
                entity:
                    label:        Email
                datagrid:
                    is_visible:   false
            owner:                Custom
            is_extend:            true

        add_fax:
            type:                 string
            configs:
                entity:
                    label:        Fax
                datagrid:
                    is_visible:   false
            owner:                Custom
            is_extend:            true

        add_website:
            type:                 string
            configs:
                entity:
                    label:        Website
                datagrid:
                    is_visible:   false
            owner:                Custom
            is_extend:            true

        add_employees:
            type:                 integer
            configs:
                entity:
                    label:        Employees
                datagrid:
                    is_visible:   false
            owner:                Custom
            is_extend:            true

        add_ownership:
            type:                 string
            configs:
                entity:
                    label:        Ownership
                datagrid:
                    is_visible:   false
            owner:                Custom
            is_extend:            true

        add_ticker_symbol:
            type:                 string
            configs:
                entity:
                    label:        Ticker Symbol
                datagrid:
                    is_visible:   false

            owner:                Custom
            is_extend:            true

        add_rating:
            type:                 string
            configs:
                entity:
                    label:        Rating
                datagrid:
                    is_visible:   false

            owner:                Custom
            is_extend:            true
