autocomplete_entities:
    accounts:
        type: flexible
        form_options:
            datasource: autocomplete
        options:
            entity_class: OroCRM\Bundle\AccountBundle\Entity\Account
        property: "name"