datagrid:
    sales-opportunity-datgrid:
        extended_entity_name: %orocrm_sales.opportunity.class%
        options:
            entityHint: opportunities
        source:
            type: orm
            acl_resource: orocrm_sales_opportunity_view
            query:
                select:
                    - o.id
                    - o.name
                    - o.closeDate
                    - o.probability
                    - CONCAT(contact.firstName, CONCAT(' ', contact.lastName)) as contactName
                    - status.label as statusLabel
                    - email.email as primaryEmail
                from:
                    - { table: %orocrm_sales.opportunity.class%, alias: o }
                join:
                    left:
                        - { join: o.contact , alias: contact }
                        - { join: o.status, alias: status }
                        - { join: contact.emails, alias: email, conditionType: WITH, condition: 'email.primary = true' }
        columns:
            name:
                label: orocrm.sales.opportunity.datagrid.name
            contactName:
                label: orocrm.sales.opportunity.datagrid.contact_name
            closeDate:
                label: orocrm.sales.opportunity.datagrid.close_date
                frontend_type: date
            probability:
                label: orocrm.sales.opportunity.datagrid.probability
                frontend_type: percent
            statusLabel:
                label: orocrm.sales.opportunity.datagrid.status
            primaryEmail:
                label: orocrm.sales.opportunity.datagrid.email
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_sales_opportunity_view
                params:     [ id ]
            update_link:
                type:       url
                route:      orocrm_sales_opportunity_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_opportunity
                params:     [ id ]
        sorters:
            columns:
                name:
                    data_name: o.name
                contactName:
                    data_name: contactName
                closeDate:
                    data_name: o.closeDate
                probability:
                    data_name: o.probability
                statusLabel:
                    data_name: status.label
                primaryEmail:
                    data_name: email.email
        filters:
            columns:
                name:
                    type: string
                    data_name: o.name
                contactName:
                    type: string
                    data_name: contactName
                    filter_by_having: true
                closeDate:
                    type: date
                    data_name: o.closeDate
                probability:
                    type: percent
                    data_name: o.probability
                statusLabel:
                    type: entity
                    data_name: status.name
                    options:
                        field_options:
                            class: OroCRMSalesBundle:OpportunityStatus
                            property: label
                primaryEmail:
                    type: string
                    data_name: email.email
                    filter_by_having: true
        actions:
            view:
                type:          navigate
                acl_resource:  orocrm_sales_opportunity_view
                label:         orocrm.sales.opportunity.datagrid.view
                icon:          user
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  orocrm_sales_opportunity_update
                label:         orocrm.sales.opportunity.datagrid.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  orocrm_sales_opportunity_delete
                label:         orocrm.sales.opportunity.datagrid.delete
                icon:          trash
                link:          delete_link
    sales-lead-datgrid:
        options:
            entityHint: leads
