parameters:
    orocrm_sales.form.type.opportunity.class: OroCRM\Bundle\SalesBundle\Form\Type\OpportunityType
    orocrm_sales.form.handler.opportunity.class: OroCRM\Bundle\SalesBundle\Form\Handler\OpportunityHandler

    orocrm_sales.lead.form.type.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadType
    orocrm_sales.lead.form.handler.class: OroCRM\Bundle\SalesBundle\Form\Handler\LeadHandler
    orocrm_sales.lead.form.type.api.class: OroCRM\Bundle\SalesBundle\Form\Type\LeadApiType

services:
    orocrm_sales.form.type.opportunity:
        class: %orocrm_sales.form.type.opportunity.class%
        tags:
            - { name: form.type, alias: orocrm_opportunity }

    orocrm_sales.form.opportunity:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_opportunity_form"
            - "orocrm_opportunity"

    orocrm_sales.form.handler.opportunity:
        class: %orocrm_sales.form.handler.opportunity.class%
        scope: request
        arguments:
            - @orocrm_sales.form.opportunity
            - @request
            - @doctrine.orm.entity_manager

    orocrm_sales.lead.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["orocrm_sales_lead_form", "orocrm_sales_lead", null]

    orocrm_sales.lead.form.type:
        class: %orocrm_sales.lead.form.type.class%
        tags:
            - { name: "form.type", alias: "orocrm_sales_lead" }

    orocrm_sales.lead.form.handler:
        class: %orocrm_sales.lead.form.handler.class%
        scope: request
        arguments:
            - @orocrm_sales.lead.form
            - @request
            - @doctrine.orm.entity_manager

    orocrm_sales.lead.form.type.api:
        class: %orocrm_sales.lead.form.type.api.class%
        tags:
            - { name: "form.type", alias: "lead" }

    orocrm_sales.lead.form.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["lead", "lead", null]

    orocrm_sales.lead.form.handler.api:
        class: %orocrm_sales.lead.form.handler.class%
        scope: request
        arguments:
            - @orocrm_sales.lead.form.type.api
            - @request
            - @doctrine.orm.entity_manager
