oro_menu_config:
    items:
        customers_tab:
            label: 'Customers'
            uri: '#'
            extras:
                position: 10
        opportunity_list:
            label: 'Opportunities'
            route: orocrm_opportunity_index
            extras:
                description: List of opportunities

        shortcut_list_opportunities:
            label: 'Show opportunities list'
            route: orocrm_opportunity_index
            extras:
                description: List of opportunities

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        opportunity_list: ~

        shortcuts:
            children:
                shortcut_list_opportunities: ~

oro_titles:
    orocrm_opportunity_index: Opportunities
    orocrm_opportunity_view: %%opportunity.topic%%
    orocrm_opportunity_create: Create Opportunity
    orocrm_opportunity_update: %%opportunity.topic%%
