oro_menu_config:
    items:
        customers_tab:
            label: 'Customers'
            uri: '#'
            extras:
                position: 10

        lead_list:
            label: 'Leads'
            route: orocrm_sales_lead_index
            extras:
                description: List of leads
        opportunity_list:
            label: 'Opportunities'
            route: orocrm_sales_opportunity_index
            extras:
                description: List of opportunities

        shortcut_list_leads:
            label: 'Show leads list'
            route: orocrm_sales_lead_index
            extras:
                description: List of leads
        shortcut_list_opportunities:
            label: 'Show opportunities list'
            route: orocrm_sales_opportunity_index
            extras:
                description: List of opportunities
        shortcut_new_lead:
            label: Create new lead
            route: orocrm_sales_lead_create
            extras:
                description: Create new lead
                isCustomAction: true
        shortcut_new_opportunity:
            label: Create new opportunity
            route: orocrm_sales_opportunity_create
            extras:
                description: Create new opportunity
                isCustomAction: true

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        lead_list: ~
                        opportunity_list: ~
        shortcuts:
            children:
                shortcut_list_leads: ~
                shortcut_list_opportunities: ~
                shortcut_new_lead: ~
                shortcut_new_opportunity: ~

oro_titles:
    orocrm_sales_opportunity_index: Opportunities
    orocrm_sales_opportunity_view: %%opportunity.topic%% - Opportunities
    orocrm_sales_opportunity_create: Create Opportunity
    orocrm_sales_opportunity_update: %%opportunity.topic%% - Opportunities
    
    orocrm_sales_lead_index: Leads
    orocrm_sales_lead_view: %%lead.topic%% - Leads
    orocrm_sales_lead_create: Create Lead
    orocrm_sales_lead_update: %%lead.topic%% - Leads
