oro_menu_config:
    items:
        customers_tab:
            label: 'Customers'
            uri: '#'
            extras:
                position: 10
        opportunity_list:
            label: 'Opportunities'
            route: orocrm_opportunity_index
            extras:
                description: List of opportunities

        lead_list:
            label: 'Leads'
            route: orocrm_sales_lead_index
            extras:
                description: List of leads

        shortcut_list_opportunities:
            label: 'Show opportunities list'
            route: orocrm_opportunity_index
            extras:
                description: List of opportunities

    tree:
        application_menu:
            children:
                customers_tab:
                    children:
                        opportunity_list: ~
                        lead_list: ~

        shortcuts:
            children:
                shortcut_list_opportunities: ~

oro_titles:
    orocrm_opportunity_index: Opportunities
    orocrm_opportunity_view: %%opportunity.topic%% - Opportunities
    orocrm_opportunity_create: Create Opportunity
    orocrm_opportunity_update: %%opportunity.topic%% - Opportunities
    
    orocrm_sales_lead_index: Leads
    orocrm_sales_lead_view: %%lead.topic%% - Leads
    orocrm_sales_lead_create: Create Lead
    orocrm_sales_lead_update: %%lead.topic%% - Leads
