query_designer:
    aggregates:
        opportunity_status:
            applicable: [{entity: OroCRM\Bundle\SalesBundle\Entity\OpportunityStatus, field: name}]
            functions:
                - { name: WonCount,        expr: SUM(CASE WHEN $column = 'won' THEN 1 ELSE 0 END) }
                - { name: LostCount,       expr: SUM(CASE WHEN $column = 'lost' THEN 1 ELSE 0 END) }
                - { name: InProgressCount, expr: SUM(CASE WHEN $column = 'in_progress' THEN 1 ELSE 0 END) }
            query_type: [report]
