parameters:
    orocrm_sales.opportunity.class: OroCRM\Bundle\SalesBundle\Entity\Opportunity
    orocrm_sales.opportunity.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    orocrm_sales.lead.entity.class: OroCRM\Bundle\SalesBundle\Entity\Lead
    orocrm_sales.lead.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    orocrm_sales.lead.datagrid_helper.class: Oro\Bundle\AddressBundle\Datagrid\CountryDatagridHelper

    orocrm_sales.funnel.entity.class: OroCRM\Bundle\SalesBundle\Entity\SalesFunnel

services:
    orocrm_sales.opportunity.manager.api:
        class: %orocrm_sales.opportunity.manager.api.class%
        arguments:
            - %orocrm_sales.opportunity.class%
            - @doctrine.orm.entity_manager

    orocrm_sales.lead.manager.api:
        class: %orocrm_sales.lead.manager.api.class%
        arguments:
            - %orocrm_sales.lead.entity.class%
            - @doctrine.orm.entity_manager

    orocrm_sales.lead.datagrid_helper:
        class: %orocrm_sales.lead.datagrid_helper.class%
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.sales-lead-datagrid, method: onBuildAfter }

    orocrm_sales.form.autocomplete.contact.search_handler:
        parent: oro_form.autocomplete.full_name.search_handler
        arguments:
            - %orocrm_sales.opportunity.class%
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: opportunities, acl_resource: orocrm_sales_opportunity_view }
