parameters:
    orocrm_sales.opportunity.class: OroCRM\Bundle\SalesBundle\Entity\Opportunity

services:
#    oro_crm_sales.example:
#        class: %oro_crm_sales.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
