OroCRM\Bundle\SalesBundle\Entity\Opportunity:
    properties:
        topic:
            - NotBlank: ~
            - Length:
                max: 255
        probability:
            - Range:
                min: 0
        budgetAmount:
            - Range:
                min: 0

OroCRM\Bundle\SalesBundle\Entity\Lead:
    properties:
        topic:
            - NotBlank: ~
            - Length:
                max: 255
        firstName:
            - NotBlank: ~
            - Length:
                max: 255
        lastName:
            - NotBlank: ~
            - Length:
                max: 255
        email:
            - Email: ~
        website:
            - Url: ~
