workflows:
    # Unqualified Sales Lead Workflow
    sales_lead:
        label: 'Unqualified Sales Lead'
        enabled: true
        type: entity
        steps:
            new:
                label: 'New'
                allowed_transitions:
                    - qualify
                    - cancel
            qualified:
                label: 'Qualified'
                allowed_transitions:
                    - reactivate
            cancelled:
                label: 'Cancelled'
                allowed_transitions:
                    - reactivate
        attributes:
            lead:
                label: 'Sales Lead'
                type: entity
                options:
                    class: OroCRM\Bundle\SalesBundle\Entity\Lead
                    managed_entity: true
        transitions:
            qualify:
                label: 'Qualify'
                step_to: qualified
                is_start: true
                options:
                    frontend:
                        icon: 'icon-ok'
                transition_definition: qualify_definition
            cancel:
                label: 'Disqualify'
                step_to: cancelled
                is_start: true
                options:
                    frontend:
                        icon: 'icon-remove'
                transition_definition: cancel_definition
            reactivate:
                label: 'Reactivate'
                step_to: new
                is_start: true
                options:
                    frontend:
                        icon: 'icon-repeat'
                transition_definition: reactivate_definition
        transition_definitions:
            qualify_definition:
                conditions: # if lead.status = "new" or lead.status is empty
                    @or:
                        - @equal: [$lead.status.name, 'new']
                        - @empty: $lead.status.name
                post_actions: # set lead.status = "qualified"
                    - @find_entity:
                          class: OroCRM\Bundle\SalesBundle\Entity\LeadStatus
                          identifier: 'qualified'
                          attribute: $lead.status
                    - @tree:
                        conditions: # if contact not specified
                            @empty: $lead.contact
                        post_actions:
                            - @create_entity: # create Contact based on Lead data
                                class: OroCRM\Bundle\ContactBundle\Entity\Contact
                                attribute: $lead.contact
                                data:
                                    firstName: $lead.firstName
                                    lastName: $lead.lastName
                                    description: $lead.topic
                            # TODO: add contact email, phone and address
            cancel_definition: # if lead.status = "new" or lead.status is empty
                conditions:
                    @or:
                        - @equal: [$lead.status.name, 'new']
                        - @empty: $lead.status.name
                post_actions: # set lead.status = "canceled"
                    - @find_entity:
                        class: OroCRM\Bundle\SalesBundle\Entity\LeadStatus
                        identifier: 'canceled'
                        attribute: $lead.status
            reactivate_definition:  # if lead.status = "qualified" or lead.status = "canceled"
                conditions:
                    @or:
                        - @equal: [$lead.status.name, 'qualified']
                        - @equal: [$lead.status.name, 'canceled']
                post_actions: # set lead.status = "new"
                    - @find_entity:
                        class: OroCRM\Bundle\SalesBundle\Entity\LeadStatus
                        identifier: 'new'
                        attribute: $lead.status

    # Qualified Sales Opportunity Workflow
    sales_opportunity:
        label: 'Qualified Sales Opportunity'
        enabled: true
        type: entity
        steps:
            new:
                label: 'New'
                allowed_transitions:
                    - close_as_won
                    - close_as_lost
            closed:
                label: 'Closed'
                allowed_transitions:
                    - reopen
        attributes:
            opportunity:
                label: Sales Opportunity
                type: entity
                options:
                    class: OroCRM\Bundle\SalesBundle\Entity\Opportunity
                    managed_entity: true
        transitions:
            close_as_won:
                label: 'Close as Won'
                step_to: closed
                is_start: true
                options:
                    frontend:
                        icon: 'icon-ok-circle'
                transition_definition: close_as_won_definition
            close_as_lost:
                label: 'Close as Lost'
                step_to: closed
                is_start: true
                options:
                    frontend:
                        icon: 'icon-remove-circle'
                transition_definition: close_as_lost_definition
            reopen:
                label: 'Reopen'
                step_to: new
                is_start: true
                options:
                    frontend:
                        icon: 'icon-repeat'
                transition_definition: reopen_definition
        transition_definitions:
            close_as_won_definition:
                conditions: # if opportunity.status = "in_progress" or opportunity.status is empty
                    @or:
                        - @equal: [$opportunity.status.name, 'in_progress']
                        - @empty: $opportunity.status.name
                post_actions: # set opportunity.status = "won"
                    - @find_entity:
                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityStatus
                        identifier: 'won'
                        attribute: $opportunity.status
            close_as_lost_definition:
                conditions: # if opportunity.status = "in_progress" or opportunity.status is empty
                    @or:
                        - @equal: [$opportunity.status.name, 'in_progress']
                        - @empty: $opportunity.status.name
                post_actions: # set opportunity.status = "lost"
                    - @find_entity:
                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityStatus
                        identifier: 'lost'
                        attribute: $opportunity.status
            reopen_definition:
                conditions: # if opportunity.status = "won" or opportunity.status = "lost"
                    @or:
                        - @equal: [$opportunity.status.name, 'won']
                        - @equal: [$opportunity.status.name, 'lost']
                post_actions: # set opportunity.status = "in_progress"
                    - @find_entity:
                        class: OroCRM\Bundle\SalesBundle\Entity\OpportunityStatus
                        identifier: 'in_progress'
                        attribute: $opportunity.status
