workflows:
    case_flow:
        transitions:
            start_progress:
                label: orocrm.case.workflow.transitions.start_progress.label
                step_to: in_progress
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-play'
                transition_definition: start_progress_definition
            stop_progress:
                label: orocrm.case.workflow.transitions.stop_progress.label
                step_to: open
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-stop'
                transition_definition: stop_progress_definition
            resolve:
                label: orocrm.case.workflow.transitions.resolve.label
                step_to: resolved
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-ok'
                transition_definition: resolve_definition
            close:
                label: orocrm.case.workflow.transitions.close.label
                step_to: closed
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-ok'
                transition_definition: closed_definition
            reopen:
                label: orocrm.case.workflow.transitions.reopen.label
                step_to: in_progress
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-edit'
                transition_definition: reopen_definition
