OroCRM\Bundle\ContactUsBundle\Entity\ContactRequest:
    properties:
        name:
            - NotBlank: ~
            - Length:
                max: 200
        emailAddress:
            - Email:    ~
            - NotBlank: ~
        comment:
            - NotBlank: ~
