connector:
    name: oro_importexport
    jobs:
        # Customer import jobs
        mage_customer_import_validation:
            title: "Entity Import Validation from Magento SOAP API"
            type: import_validation
            steps:
                import_validation:
                    title:     import_validation
                    reader:    orocrm_magento.import.customer_reader.magento_api
                    processor: oro_importexport.processor.import_validation_delegate
                    writer:    oro_importexport.writer.doctrine_clear

        mage_customer_import:
            title: "Entity Import from Magento SOAP API"
            type: import
            steps:
                import:
                    title:     import
                    reader:    orocrm_magento.import.customer_reader.magento_api
                    processor: oro_importexport.processor.import_delegate
                    writer:    oro_importexport.writer.entity

        # Region import jobs
        mage_regions_import:
            title: "Import Magento regions via SOAP API"
            type: import
            steps:
                import:
                    title:     import
                    reader:    orocrm_magento.import.region_reader.magento_api
                    processor: oro_importexport.processor.import_delegate
                    writer:    oro_importexport.writer.entity

        mage_regions_import_validation:
            title: "Validate Magento regions via SOAP API"
            type: import_validation
            steps:
                import_validation:
                    title:     import_validation
                    reader:    orocrm_magento.import.region_reader.magento_api
                    processor: oro_importexport.processor.import_validation_delegate
                    writer:    oro_importexport.writer.doctrine_clear

        # Cart import jobs
        mage_cart_import_validation:
            title: "Import validation Magento carts (quote) from Magento"
            type: import_validation
            steps:
                import_validation:
                    title:     import_validation
                    reader:    orocrm_magento.import.cart_reader.magento_api
                    processor: oro_importexport.processor.import_validation_delegate
                    writer:    oro_importexport.writer.doctrine_clear

        mage_cart_import:
            title: "Import validation Magento carts (quote) from Magento"
            type: import
            steps:
                import:
                    title:     import
                    reader:    orocrm_magento.import.cart_reader.magento_api
                    processor: oro_importexport.processor.import_delegate
                    writer:    oro_importexport.writer.entity
