connector:
    name: oro_importexport
    jobs:
        # Customer import jobs
        mage_customer_import_validation:
            title: "Entity Import Validation from Magento SOAP API"
            type: import_validation
            steps:
                import_validation:
                    title:     import_validation
                    services:
                        reader:    orocrm_magento.mage.customer_connector
                        processor: oro_importexport.processor.import_validation_delegate
                        writer:    oro_importexport.writer.doctrine_clear
                    parameters:
                        batch_size: 15

        mage_customer_import:
            title: "Entity Import from Magento SOAP API"
            type: import
            steps:
                import:
                    title:     import
                    services:
                        reader:    orocrm_magento.mage.customer_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 15

        # Region import jobs
        mage_regions_import:
            title: "Import Magento regions via SOAP API"
            type: import
            steps:
                import:
                    title:     import
                    services:
                        reader:    orocrm_magento.mage.region_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 15

        mage_regions_import_validation:
            title: "Validate Magento regions via SOAP API"
            type: import_validation
            steps:
                import_validation:
                    title:     import_validation
                    services:
                        reader:    orocrm_magento.mage.region_connector
                        processor: oro_importexport.processor.import_validation_delegate
                        writer:    oro_importexport.writer.doctrine_clear
                    parameters:
                        batch_size: 15

        # Magento orders import/update
        mage_order_import_validation:
            title: "Order Import Validation from Magento SOAP API"
            type: import_validation
            steps:
                import_validation:
                    title:     import_validation
                    services:
                        reader:    orocrm_magento.mage.order_connector
                        processor: oro_importexport.processor.import_validation_delegate
                        writer:    oro_importexport.writer.doctrine_clear
                    parameters:
                        batch_size: 15

        mage_order_import:
            title: "Order Import from Magento SOAP API"
            type: import
            steps:
                import:
                    title:     import
                    services:
                        reader:    orocrm_magento.mage.order_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 15

        # Cart import jobs
        mage_cart_import_validation:
            title: "Import Validation Magento carts (quote) from Magento"
            type: import_validation
            steps:
                import_validation:
                    title:     import_validation
                    services:
                        reader:    orocrm_magento.mage.cart_connector
                        processor: oro_importexport.processor.import_validation_delegate
                        writer:    oro_importexport.writer.doctrine_clear
                    parameters:
                        batch_size: 15

        mage_cart_import:
            title: "Import Magento carts (quote) from Magento"
            type: import
            steps:
                import:
                    title:     import
                    services:
                        reader:    orocrm_magento.mage.cart_connector
                        processor: oro_importexport.processor.import_delegate
                        writer:    oro_importexport.writer.entity
                    parameters:
                        batch_size: 15
