connector:
    name: oro_importexport
    jobs:
        mage_customer_import_validation:
            title: "Entity Import Validation from Magento SOAP API"
            type: import_validation
            steps:
                import_validation:
                    title:     import_validation
                    reader:    orocrm_magento.import.reader.magento_api
                    processor: oro_importexport.processor.import_validation_delegate
                    writer:    oro_importexport.writer.doctrine_clear

        mage_customer_import:
            title: "Entity Import Validation from Magento SOAP API"
            type: import
            steps:
                import:
                    title:     import
                    reader:    oro_importexport.reader.csv
                    processor: oro_importexport.processor.import_delegate
                    writer:    oro_importexport.writer.entity
