datagrid:
    magento-customers-grid:
        source:
            type: orm
            acl_resource: orocrm_magento_customer_view
            query:
                select:
                    - c
                from:
                    - { table: OroCRMMagentoBundle:Customer , alias: c }
        properties:
            id: ~
            view_link:
                type: url
                route: orocrm_magento_customer_view
                params: [ id ]

        actions:
            view:
                type:         navigate
                label:        orocrm.magento.datagrid.actions.view.label
                link:         view_link
                icon:         user
                acl_recource: orocrm_magento_customer_view
                rowAction:    true

        options:
            entityHint: customer
