parameters:
    # entities
    orocrm_magento.customer.entity.class:                                 OroCRM\Bundle\MagentoBundle\Entity\Customer
    orocrm_magento.region.entity.class:                                   OroCRM\Bundle\MagentoBundle\Entity\Region

    # connectors
    orocrm_magento.mage.region_connector.class:                           OroCRM\Bundle\MagentoBundle\Provider\RegionConnector
    orocrm_magento.mage.customer_connector.class:                         OroCRM\Bundle\MagentoBundle\Provider\CustomerConnector
    orocrm_magento.mage.store_connector.class:                            OroCRM\Bundle\MagentoBundle\Provider\StoreConnector
    orocrm_magento.mage.product_connector.class:                          OroCRM\Bundle\MagentoBundle\Provider\ProductConnector
    orocrm_magento.mage.order_connector.class:                            OroCRM\Bundle\MagentoBundle\Provider\OrderConnector

    # normalizers
    orocrm_magento.importexport.normalizer.customer.class:                OroCRM\Bundle\MagentoBundle\ImportExport\Serializer\CustomerNormalizer
    orocrm_magento.importexport.normalizer.region.class:                  OroCRM\Bundle\MagentoBundle\ImportExport\Serializer\RegionNormalizer
    orocrm_magento.importexport.relation_normalizer.class:                OroCRM\Bundle\MagentoBundle\ImportExport\Serializer\RelationNormalizer
    orocrm_magento.importexport.typed_address_normalizer.class:           OroCRM\Bundle\MagentoBundle\ImportExport\Serializer\MagentoAddressNormalizer

    # strategies
    orocrm_magento.import_strategy.customer.add_or_update.class:          OroCRM\Bundle\MagentoBundle\ImportExport\Strategy\AddOrUpdateCustomer
    orocrm_magento.import_strategy.region.add_or_update.class:            OroCRM\Bundle\MagentoBundle\ImportExport\Strategy\RegionStrategy

services:
    # Connectors
    orocrm_magento.mage.customer_connector:
        class: %orocrm_magento.mage.customer_connector.class%
        arguments:
          - @oro_importexport.context_registry
          - @orocrm_magento.mage.store_connector
          - @oro_integration.logger.strategy
        tags:
          - { name: oro_integration.connector, type: customer, channel_type: magento }

    orocrm_magento.mage.product_connector:
        class: %orocrm_magento.mage.product_connector.class%
        arguments:
          - @oro_importexport.context_registry
          - @oro_integration.logger.strategy
        tags: []
          # @TODO uncomment when feature will be full implemented
          # - { name: oro_integration.connector, type: product, channel_type: magento }

    orocrm_magento.mage.order_connector:
        class: %orocrm_magento.mage.order_connector.class%
        arguments:
          - @oro_importexport.context_registry
          - @oro_integration.logger.strategy
        tags:
          - { name: oro_integration.connector, type: order, channel_type: magento }

    orocrm_magento.mage.store_connector: # for customer, etc connectors only
        class: %orocrm_magento.mage.store_connector.class%
        arguments:
          - @oro_importexport.context_registry
          - @oro_integration.logger.strategy

    orocrm_magento.mage.region_connector:
        class: %orocrm_magento.mage.region_connector.class%
        arguments:
          - @oro_importexport.context_registry
          - @oro_integration.logger.strategy
        tags:
          - { name: oro_integration.connector, type: region, channel_type: magento }

    # Normalizers
    orocrm_magento.importexport.normalizer.customer:
        class: %orocrm_magento.importexport.normalizer.customer.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_magento.importexport.normalizer.region:
        class: %orocrm_magento.importexport.normalizer.region.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_magento.importexport.magento_address_normalizer:
        class: %orocrm_magento.importexport.typed_address_normalizer.class%
        arguments: [@oro_address.importexport.address_normalizer]
        tags:
            - { name: oro_importexport.normalizer, priority: -1 }

    orocrm_magento.importexport.relation_normalizer:
        class: %orocrm_magento.importexport.relation_normalizer.class%
        tags:
            - { name: oro_importexport.normalizer, priority: -10 }

    # Strategies
    orocrm_magento.import.strategy.customer.add_or_update:
        class: %orocrm_magento.import_strategy.customer.add_or_update.class%
        arguments:
            - @oro_importexport.strategy.import.helper

    orocrm_magento.import.strategy.region.add_or_update:
        class: %orocrm_magento.import_strategy.region.add_or_update.class%
        arguments:
            - @oro_importexport.strategy.import.helper

    # Processors
    orocrm_magento.importexport.processor.import_customer:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@oro_importexport.data_converter.default]]
             - [setStrategy, [@orocrm_magento.import.strategy.customer.add_or_update]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %orocrm_magento.customer.entity.class%, alias: orocrm_magento.add_or_update_customer }
            - { name: oro_importexport.processor, type: import_validation, entity: %orocrm_magento.customer.entity.class%, alias: orocrm_magento.add_or_update_customer }

    orocrm_magento.importexport.processor.import_region:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@oro_importexport.data_converter.default]]
             - [setStrategy, [@orocrm_magento.import.strategy.region.add_or_update]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %orocrm_magento.region.entity.class%, alias: orocrm_magento.add_or_update_region }
            - { name: oro_importexport.processor, type: import_validation, entity: %orocrm_magento.region.entity.class%, alias: orocrm_magento.add_or_update_region }
