oro_menu_config:
    items:
        magento_customers_list:
            label: 'Magento'
            route: 'orocrm_magento_customer_index'
            extras:
                routes: ['/^orocrm_magento_customer_(index|view)+$/']
                description: List of customers from "Magento type channels"
        magento_product_list:
            label: 'Magento'
            route: 'orocrm_magento_product_index'
            extras:
                routes: ['/^orocrm_magento_product_(index|view)+$/']
                description: List of products from "Magento type channels"
        channels_submenu:
            label: 'Channels'
            uri: '#'
        products_tab:
            label: 'Products'
            uri: '#'

    tree:
        application_menu:
            children:
                # @TODO uncomment when feature will be full implemented
#                products_tab:
#                    children:
#                        channels_submenu: ~
#                                magento_product_list: ~
                customers_tab:
                    children:
                        channels_submenu:
                            children:
                                magento_customers_list: ~

oro_titles:
    orocrm_magento_customer_index: ~
    orocrm_magento_customer_view:  %%customer.name%%
    orocrm_magento_product_index:  ~
    orocrm_magento_product_view:   %%product.name%%
