oro_menu_config:
    items: []
#        magento_customers_list:
#            label: 'Customers'
#            route: 'orocrm_magento_customer_index'
#            extras:
#                routes: ['/^orocrm_magento_customer_(index|view)+$/']
#        magento_product_list:
#            label: 'Products'
#            route: 'orocrm_magento_product_index'
#            extras:
#                routes: ['/^orocrm_magento_product_(index|view)+$/']
#        magento_cart_list:
#            label: 'Shopping Carts'
#            route: 'orocrm_magento_cart_index'
#            extras:
#                routes: ['/^orocrm_magento_cart_(index|view)+$/']

oro_titles:
    orocrm_magento_customer_index: ~
    orocrm_magento_customer_view:  %%customer.name%%
    orocrm_magento_cart_index:     ~
    orocrm_magento_cart_view:      "Cart #%%cart.id%%"
    orocrm_magento_order_index:    ~
    orocrm_magento_order_view:     "Cart #%%cart.originalId%%"
    orocrm_magento_product_index:  ~
    orocrm_magento_product_view:   %%product.name%%
