placeholders:
    orocrm_account_customers_info:
        items:
            orocrm_account_customers_info_widget: ~
    orocrm_account_orders:
        items:
            orocrm_account_orders_grid: ~

items:
    orocrm_account_customers_info_widget:
        template: OroCRMMagentoBundle:Customer:accountsWidgetPlaceholder.html.twig
    orocrm_account_orders_grid:
        template: OroCRMMagentoBundle:Order:accountOrdersPlaceholder.html.twig
