parameters:
    orocrm_magento.mage.customer_connector.class: OroCRM\Bundle\MagentoBundle\Provider\CustomerConnector
    orocrm_magento.mage.soap_transport.class:     OroCRM\Bundle\MagentoBundle\Provider\MageSoapTransport
    orocrm_magento.mage.db_transport.class:       OroCRM\Bundle\MagentoBundle\Provider\MageDBTransport

    orocrm_magento.provider.channel_type.class:   OroCRM\Bundle\MagentoBundle\Provider\MageChannelType

services:
    orocrm_magento.mage.soap_transport:
        class: %orocrm_magento.mage.soap_transport.class%

    orocrm_magento.mage.db_transport:
        class: %orocrm_magento.mage.db_transport.class%
        arguments:
            - @doctrine.dbal.connection_factory

    orocrm_magento.mage.customer_connector:
        class: %orocrm_magento.mage.customer_connector.class%
        arguments:
            - @oro_integration.mage.soap_transport

    orocrm_magento.provider.channel_type:
        class: %orocrm_magento.provider.channel_type.class%
        tags:
            - { name: oro_integration.channel, type: magento }
