parameters:
    orocrm_magento.customer.entity.class:         OroCRM\Bundle\MagentoBundle\Entity\Customer
    orocrm_magento.mage.customer_connector.class: OroCRM\Bundle\MagentoBundle\Provider\CustomerConnector
    orocrm_magento.mage.soap_transport.class:     OroCRM\Bundle\MagentoBundle\Provider\MageSoapTransport
    orocrm_magento.mage.db_transport.class:       OroCRM\Bundle\MagentoBundle\Provider\MageDBTransport
    orocrm_magento.mage.sync_processor.class:     OroCRM\Bundle\MagentoBundle\Provider\SyncProcessor

    orocrm_magento.importexport.normalizer.customer.class:       OroCRM\Bundle\MagentoBundle\ImportExport\Serializer\CustomerNormalizer
    orocrm_magento.importexport.relation_normalizer.class:          OroCRM\Bundle\MagentoBundle\ImportExport\Serializer\RelationNormalizer

    orocrm_magento.import_strategy.customer.add_or_update.class: OroCRM\Bundle\MagentoBundle\ImportExport\Strategy\AddOrUpdateCustomer
    orocrm_magento.import.reader.magento_api.class:              OroCRM\Bundle\MagentoBundle\ImportExport\Reader\CustomerApiReader

    orocrm_magento.provider.channel_type.class:                  OroCRM\Bundle\MagentoBundle\Provider\MageChannelType
    orocrm_magento.form.type.soap_transport_setting.class:       OroCRM\Bundle\MagentoBundle\Form\Type\SoapTransportSettingFormType
    orocrm_magento.form.type.customer_connector_setting.class:   OroCRM\Bundle\MagentoBundle\Form\Type\CustomerConnectorSettingFormType

services:
    orocrm_magento.mage.soap_transport:
        class: %orocrm_magento.mage.soap_transport.class%
        tags:
            - { name: oro_integration.transport, type: magento_soap, channel_type: magento }

    orocrm_magento.mage.customer_connector:
        class: %orocrm_magento.mage.customer_connector.class%
        arguments:
          - @orocrm_magento.mage.soap_transport
        tags:
          - { name: oro_integration.connector, type: customer, channel_type: magento }

    # customer sync processor
    orocrm_magento.customer_sync.processor:
        class: %orocrm_magento.mage.sync_processor.class%
        arguments:
          - @doctrine.orm.entity_manager
          - @oro_importexport.processor.registry
          - @oro_importexport.job_executor
          - @orocrm_magento.mage.customer_connector

    # customer normalizer/denormalizer
    orocrm_magento.importexport.normalizer.customer:
        class: %orocrm_magento.importexport.normalizer.customer.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_magento.importexport.relation_normalizer:
        class: %orocrm_magento.importexport.relation_normalizer.class%
        tags:
            - { name: oro_importexport.normalizer, priority: -10 }

    orocrm_magento.import.strategy.customer.add_or_update:
        class: %orocrm_magento.import_strategy.customer.add_or_update.class%
        arguments:
            - @oro_importexport.strategy.import.helper

    # import processor
    orocrm_magento.importexport.processor.import_customer:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@oro_importexport.data_converter.default]]
             - [setStrategy, [@orocrm_magento.import.strategy.customer.add_or_update]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %orocrm_magento.customer.entity.class%, alias: orocrm_magento.add_or_update_customer }
            - { name: oro_importexport.processor, type: import_validation, entity: %orocrm_magento.customer.entity.class%, alias: orocrm_magento.add_or_update_customer }

    orocrm_magento.import.reader.magento_api:
        class: %orocrm_magento.import.reader.magento_api.class%
        arguments:
            - @oro_importexport.context_registry
            - @orocrm_magento.mage.customer_connector

    orocrm_magento.provider.channel_type:
        class: %orocrm_magento.provider.channel_type.class%
        tags:
            - { name: oro_integration.channel, type: magento }

    orocrm_magento.form.type.soap_transport_setting:
        class: %orocrm_magento.form.type.soap_transport_setting.class%
        arguments:
            - @orocrm_magento.mage.soap_transport
            - @oro_security.encoder.mcrypt
        tags:
            - { name: form.type, alias: orocrm_magento_soap_transport_setting_form_type }

    orocrm_magento.form.type.customer_connector_setting:
        class: %orocrm_magento.form.type.customer_connector_setting.class%
        arguments:
            - @orocrm_magento.mage.customer_connector
        tags:
            - { name: form.type, alias: orocrm_magento_customer_connector_setting_form_type }
