parameters:
    orocrm_magento.customer.entity.class:         OroCRM\Bundle\MagentoBundle\Entity\Customer
    orocrm_magento.mage.customer_connector.class: OroCRM\Bundle\MagentoBundle\Provider\CustomerConnector
    orocrm_magento.mage.soap_transport.class:     OroCRM\Bundle\MagentoBundle\Provider\MageSoapTransport
    orocrm_magento.mage.db_transport.class:       OroCRM\Bundle\MagentoBundle\Provider\MageDBTransport

    orocrm_magento.importexport.normalizer.customer.class: OroCRM\Bundle\MagentoBundle\ImportExport\Serializer\CustomerNormalizer
    orocrm_magento.import_strategy.customer.add_or_update.class: OroCRM\Bundle\MagentoBundle\ImportExport\Strategy\AddOrUpdateCustomer

services:
    orocrm_magento.mage.soap_transport:
        class: %orocrm_magento.mage.soap_transport.class%

    orocrm_magento.mage.db_transport:
        class: %orocrm_magento.mage.db_transport.class%
        arguments:
          - @doctrine.dbal.connection_factory

    orocrm_magento.mage.customer_connector:
        class: %orocrm_magento.mage.customer_connector.class%
        arguments:
          - @orocrm_magento.mage.soap_transport

    # customer normalizer/denormalizer
    orocrm_magento.importexport.normalizer.customer:
        class: %orocrm_magento.importexport.normalizer.customer.class%
        tags:
            - { name: oro_importexport.normalizer }

    orocrm_magento.import.strategy.customer.add_or_update:
        class: %orocrm_magento.import_strategy.customer.add_or_update.class%

    # import processor
    orocrm_magento.importexport.processor.import_customer:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@oro_importexport.data_converter.default]]
             - [setStrategy, [@orocrm_magento.import.strategy.customer.add_or_update]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %orocrm_magento.customer.entity.class%, alias: orocrm_magento.add_or_update_customer }
            - { name: oro_importexport.processor, type: import_validation, entity: %orocrm_magento.customer.entity.class%, alias: orocrm_magento.add_or_update_customer }
