datagrid:
    campaing-grid:
        extended_entity_name: OroCRM\Bundle\CampaignBundle\Entity\Campaign
        source:
            type: orm
            acl_resource: orocrm_campaign_view
            query:
                select:
                    - c.id
                    - c.name
                    - c.code
                    - c.startDate
                    - c.endDate
                    - c.budget
                    - bu.name as ownerName
                    - org.currency as currency
                from:
                    - { table: OroCRM\Bundle\CampaignBundle\Entity\Campaign, alias: c }
                join:
                    left:
                        - { join: c.owner, alias: bu }
                        - { join: bu.organization, alias: org }
        columns:
            name:
                label: orocrm.campaign.name.label
            code:
                label: orocrm.campaign.code.label
            startDate:
                label: orocrm.campaign.start_date.label
                type: twig
                frontend_type: html
                template: OroCRMCampaignBundle:Campaign:Datagrid/date.html.twig
            endDate:
                label: orocrm.campaign.end_date.label
                type: twig
                frontend_type: html
                template: OroCRMCampaignBundle:Campaign:Datagrid/date.html.twig
            budget:
                label: orocrm.campaign.budget.label
                type:   localized_number
                method: formatCurrency
                context_resolver: OroCRM\Bundle\CampaignBundle\Grid\FormatterContextResolver::getResolverCurrencyClosure
            ownerName:
                label: orocrm.campaign.owner.label
        filters:
            columns:
                name:
                    type:        string
                    data_name:   c.name
                code:
                    type:        string
                    data_name:   c.code
                startDate:
                    type:        date
                    data_name:   c.startDate
                endDate:
                    type:        date
                    data_name:   c.endDate
                budget:
                    type:        number
                    data_name:   c.budget
                ownerName:
                    type:        entity
                    data_name:   bu.id
                    options:
                        field_options:
                            class: OroOrganizationBundle:BusinessUnit
                            property: name
        sorters:
            columns:
                name:        { data_name: c.name }
                code:        { data_name: c.code }
                startDate:   { data_name: c.startDate }
                endDate:     { data_name: c.endDate }
                budget:      { data_name: c.budget }
            default:
                startDate:  DESC
        properties:
            id: ~
            view_link:
                type: url
                route: orocrm_campaign_view
                params: [ id ]
        actions:
            view:
                type:         navigate
                label:        orocrm.campaign.datagrid.actions.view.label
                link:         view_link
                icon:         eye-open
                acl_recource: orocrm_campaign_view
                rowAction:    true
