oro_menu_config:
    items:
        marketing_tab:
            label: 'orocrm.campaign.menu.marketing_tab.label'
            uri: '#'
            extras:
                position: 30
        campaigns_list:
            label: 'orocrm.campaign.entity_plural_label'
            uri: '#'
            extras:
                position: 10
    tree:
        application_menu:
            children:
                marketing_tab:
                    children:
                        campaigns_list: ~
