datagrid:
    cases-grid:
        source:
            type: orm
            acl_resource: orocrm_case_view
            query:
                select:
                    - caseEntity.id
                    - caseEntity.id as caseNumber
                    - caseEntity.subject
                    - CONCAT(relatedCustomer.firstName, CONCAT(' ', relatedCustomer.lastName)) as customerName
                    - reporter.id as reporterId
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - caseEntity.reportedAt
                    - caseEntity.closedAt
                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as assignedTo
                    - owner.id as ownerId
                    - |
                        (CASE
                              when relatedOrder IS NOT NULL
                              THEN relatedOrder.id
                              when relatedOpportunity IS NOT NULL
                              THEN relatedOpportunity.id
                              when relatedLead IS NOT NULL
                              THEN relatedLead.id
                              when relatedCart IS NOT NULL
                              THEN relatedCart.id
                              else ''
                        END) as itemNumber
                    - workflowStep.label as workflowStepLabel
                from:
                    - { table: %orocrm_case.entity.class%, alias: caseEntity }
                join:
                    left:
                        - { join: caseEntity.reporter, alias: reporter }
                        - { join: caseEntity.relatedContact, alias: relatedContact }
                        - { join: caseEntity.relatedCustomer, alias: relatedCustomer }
                        - { join: caseEntity.owner, alias: owner }
                        - { join: caseEntity.origin, alias: origin }
                        - { join: caseEntity.relatedOrder, alias: relatedOrder }
                        - { join: caseEntity.relatedOpportunity, alias: relatedOpportunity }
                        - { join: caseEntity.relatedLead, alias: relatedLead }
                        - { join: caseEntity.relatedCart, alias: relatedCart }
                        - { join: caseEntity.workflowStep, alias: workflowStep }
        columns:
            caseNumber:
                label: orocrm.case.datagrid.case_number.label
            subject:
                label: orocrm.case.datagrid.subject.label
            reporterName:
                type: twig
                label: orocrm.case.datagrid.reporter.label
                frontend_type: html
                template: OroCRMCaseBundle:Case:Datagrid/Property/reporter.html.twig
            assignedTo:
                type: twig
                label: orocrm.case.datagrid.assigned_to.label
                frontend_type: html
                template: OroCRMCaseBundle:Case:Datagrid/Property/owner.html.twig
            reportedAt:
                label: orocrm.case.datagrid.reported_on.label
                frontend_type: datetime
            closedAt:
                label: orocrm.case.datagrid.closed_on.label
                frontend_type: datetime
            workflowStepLabel:
                label: orocrm.case.datagrid.workflow_status.label
        filters:
            columns:
                subject:
                    type: string
                    data_name: caseEntity.subject
                assignedTo:
                    type: string
                    data_name: assignedTo
                reportedAt:
                    type: datetime
                    data_name: caseEntity.reportedAt
                closedAt:
                    type: datetime
                    data_name: caseEntity.closedAt
                reporterName:
                    label: orocrm.case.datagrid.reporter.label
                    type: string
                    data_name: reporterName
                customer:
                    label: orocrm.case.datagrid.customer.label
                    type: string
                    data_name: customerName
                    enabled: false
                item:
                    label: orocrm.case.datagrid.item.label
                    type: string
                    data_name: itemNumber
                    enabled: false
                origin:
                    label: orocrm.case.datagrid.origin.label
                    type: entity
                    enabled: false
                    data_name: origin.label
                    options:
                        field_options:
                            class: OroCRMCaseBundle:CaseOrigin
                            property: label
                workflowStepLabel:
                    type:      entity
                    data_name: caseEntity.status
                    options:
                        field_type: oro_workflow_step_select
                        field_options:
                            workflow_entity_class: %orocrm_case.entity.class%

        sorters:
            columns:
                subject:
                    data_name: caseEntity.subject
                caseNumber:
                    data_name: caseEntity.id
                reporterName:
                    data_name: reporterName
                assignedTo:
                    data_name: assignedTo
                reportedAt:
                    data_name: caseEntity.reportedAt
                closedAt:
                    data_name: caseEntity.closedAt
                workflowStepLabel:
                    data_name: workflowStep.stepOrder
            default:
                reportedAt: DESC
        properties:
            id: ~
            view_link:
                type:       url
                route:      orocrm_case_view
                params:     [ id ]
            update_link:
                type:       url
                route:      orocrm_case_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      orocrm_api_delete_case
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  orocrm_case_view
                label:         View
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  orocrm_case_update
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  orocrm_case_delete
                label:         Delete
                icon:          trash
                link:          delete_link

    account-cases-grid:
        extends: cases-grid
        source:
            query:
                join:
                    left:
                        - { join: relatedOrder.customer, alias: relatedOrderCustomer }
                        - { join: relatedCart.customer, alias: relatedCartCustomer }
                        - { join: relatedContact.accounts, alias: relatedContactAccount }

                where:
                    and:
                        - |
                            relatedCustomer.account = :id
                            OR relatedContactAccount.id = :id
                            OR relatedOrderCustomer.account = :id
                            OR relatedCartCustomer.account = :id
                            OR relatedLead.account = :id
                            OR relatedOpportunity.account = :id

                groupBy: caseEntity.id

    contact-cases-grid:
        extends: cases-grid
        source:
            query:
                where:
                    and:
                        - relatedContact.id = :id

    customer-cases-grid:
        extends: cases-grid
        source:
            query:
                where:
                    and:
                        - relatedCustomer.id = :id

    order-cases-grid:
        extends: cases-grid
        source:
            query:
                where:
                    and:
                        - relatedOrder.id = :id

    cart-cases-grid:
        extends: cases-grid
        source:
            query:
                where:
                    and:
                        - relatedCart.id = :id

    lead-cases-grid:
        extends: cases-grid
        source:
            query:
                where:
                    and:
                        - relatedLead.id = :id

    opportunity-cases-grid:
        extends: cases-grid
        source:
            query:
                where:
                    and:
                        - relatedOpportunity.id = :id
