oro_menu_config:
    items:
        orocrm_case_index:
            label: 'orocrm.case.menu.index.label'
            route: 'orocrm_case_index'
            extras:
                position: 30

    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        orocrm_case_index: ~

oro_titles:
    orocrm_case_index: ~
